DROP FUNCTION IF EXISTS insert_data();
CREATE OR REPLACE FUNCTION insert_data() RETURNS SETOF integer AS
$BODY$
BEGIN
--创建社区
INSERT INTO COMMUNITIES
	(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('辽宁省社区', '辽宁省', 1, 1);
INSERT INTO COMMUNITIES
	(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('大连市社区', '大连市区域', 1, 2);

--创建机构
INSERT INTO COMPANIES
	(COMMUNITYUNIQUEID, COMPANYNAME,PROVINCE,CITY,PREFECTURE,DISTRICT, ADDRESS,HASSTOREHOUSE,STOREHOUSEUNIQUEID,IGNORECHECKER) VALUES (2, '大连市车管所','辽宁省','大连市','','中山区','大连市中山区',1,0,0);
--创建机构
INSERT INTO COMPANIES
	(COMMUNITYUNIQUEID, COMPANYNAME,PROVINCE,CITY,PREFECTURE,DISTRICT, ADDRESS,HASSTOREHOUSE,STOREHOUSEUNIQUEID,IGNORECHECKER) VALUES (2, '4S店','辽宁省','大连市','','甘井子区','大连市甘井子区12',0,0,0);
--创建机构
INSERT INTO COMPANIES
	(COMMUNITYUNIQUEID, COMPANYNAME,PROVINCE,CITY,PREFECTURE,DISTRICT, ADDRESS,HASSTOREHOUSE,STOREHOUSEUNIQUEID,IGNORECHECKER) VALUES (2, '大连二手车交易市场','辽宁省','大连市','','甘井子区','大连市甘井子区20高中',0,0,1);
	
	
--创建用户
INSERT INTO USERS
	(USERNAME, HASHED, ACTIVATED
	, COMPANYNAME, COMPANYUNIQUEID, COMMUNITYUNIQUEID, EMAIL, PHONE, FAX)
VALUES ('system', '$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO', 1
	, '', 0, 0, 'kamran@rs.com', '047-5831-01', NULL);
	
INSERT INTO USERS
	(USERNAME,HASHED, ACTIVATED
	, COMPANYNAME, COMPANYUNIQUEID, COMMUNITYUNIQUEID, EMAIL, PHONE, FAX)
VALUES ('a','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO', 1
	,'4S店', 2, 2, 'phil@rs.com', '047-5831-02', NULL);
	
INSERT INTO USERS
	(USERNAME,HASHED, ACTIVATED
	, COMPANYNAME, COMPANYUNIQUEID, COMMUNITYUNIQUEID, EMAIL, PHONE, FAX)
VALUES ('b','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO', 1
	,'大连市车管所', 1, 2, 'chris@rs.com', '047-5831-03', NULL);
	
INSERT INTO USERS
	(USERNAME,HASHED, ACTIVATED
	, COMPANYNAME, COMPANYUNIQUEID, COMMUNITYUNIQUEID, EMAIL, PHONE, FAX)
VALUES ('c','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO', 1
	,'大连市车管所', 1, 2,'liz@rs.com', '047-5831-04', NULL);
	
INSERT INTO USERS
	(USERNAME,HASHED, ACTIVATED
	, COMPANYNAME, COMPANYUNIQUEID, COMMUNITYUNIQUEID, EMAIL, PHONE, FAX)
VALUES ('d','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO', 1
	,'大连市车管所', 1, 2,'marco@rs.com', '047-5831-05', NULL);

INSERT INTO USERS
	(USERNAME,HASHED, ACTIVATED
	, COMPANYNAME, COMPANYUNIQUEID, COMMUNITYUNIQUEID, EMAIL, PHONE, FAX)
VALUES ('e','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO', 1
	,'大连市车管所', 1, 2,'ee@rs.com', '047-5831-32', NULL);
	
INSERT INTO USERPROFILES
	(USERUNIQUEID, TITLE, PICTURE, MANAGERUNIQUEID, CREATEDBY, CREATORUNIQUEID
	, DATECREATED, DATELASTMODIFIED, LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
VALUES (1, '系统管理员', 'img/adminmenu/users/user1.png', 5, 'system', 1
	, CURRENT_TIMESTAMP, NULL, NULL,'','','','','操','曹');
	
INSERT INTO USERPROFILES
	(USERUNIQUEID, TITLE, PICTURE, MANAGERUNIQUEID, CREATEDBY, CREATORUNIQUEID
	, DATECREATED, DATELASTMODIFIED, LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
VALUES (2, '职员', 'img/adminmenu/users/user2.png', 5, 'system', 1
	, CURRENT_TIMESTAMP, NULL, NULL,'','','','','权','孙');

INSERT INTO USERPROFILES
	(USERUNIQUEID, TITLE, PICTURE, MANAGERUNIQUEID, CREATEDBY, CREATORUNIQUEID
	, DATECREATED, DATELASTMODIFIED, LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
VALUES (3, '职员', 'img/adminmenu/users/user3.png', 5, 'system', 1
	, CURRENT_TIMESTAMP, NULL, NULL,'','','','','备','刘');

INSERT INTO USERPROFILES
	(USERUNIQUEID, TITLE, PICTURE, MANAGERUNIQUEID, CREATEDBY, CREATORUNIQUEID
	, DATECREATED, DATELASTMODIFIED, LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
VALUES (4, '职员', 'img/adminmenu/users/user4.png', 5, 'system', 1
	, CURRENT_TIMESTAMP, NULL, NULL,'','','','','葛亮','诸');

INSERT INTO USERPROFILES
	(USERUNIQUEID, TITLE, PICTURE, MANAGERUNIQUEID, CREATEDBY, CREATORUNIQUEID
	, DATECREATED, DATELASTMODIFIED, LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
VALUES (5, '主任', 'img/adminmenu/users/user5.png', 0, 'system', 1
	, CURRENT_TIMESTAMP, NULL, NULL,'','','','','马懿','司');
	
INSERT INTO USERPROFILES
	(USERUNIQUEID, TITLE, PICTURE, MANAGERUNIQUEID, CREATEDBY, CREATORUNIQUEID
	, DATECREATED, DATELASTMODIFIED, LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
VALUES (6, '职员', 'img/adminmenu/users/user6.png', 0, 'system', 1
	, CURRENT_TIMESTAMP, NULL, NULL,'','','','','飞','张');
	
--权限类别
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('登录类别');--A
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('个人配置');--B
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理用户');--C
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理角色');--D	
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理权限');--E
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理机构');--F
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理社区');--G
--INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理审批');--H
--INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理邀请');--I
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理租户');--J
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理站点');--K
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('广播消息');--L
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('数据字典');--M
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('业务类型');--N
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('系统参数');--O
INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理级别');--P

--权限
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A1','管理员','管理员');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A2','前台','前台用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A3','质检','质检用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A4','审档','审档用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A5','查询','数据查询用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A6','上架下架','上架下架用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B1','更改个人资料','更改个人资料');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B2','更改密码','更改密码');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C1','创建','创建用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C2','编辑','编辑用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C3','删除','删除用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C4','查看','查看用户列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C5','分配角色','为用户分配角色');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D1','创建','创建角色');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D2','编辑','编辑角色');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D3','删除','删除角色');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D4','分配用户','为角色分配用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D5','设置权限','为角色分配权限');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D6','查看','查看角色列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E1','分配角色','为权限分配角色');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E2','编辑','编辑权限');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E3','查看','查看权限列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F1','创建','创建机构');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F2','编辑','编辑机构');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F3','删除','删除机构');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F4','分配用户','为机构分配用户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F5','管理库房','管理库房');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F6','查看','查看机构列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F7','设置','设置业务类型');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G1','创建','创建社区');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G2','编辑','编辑社区');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G3','删除','删除社区');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G4','分配机构','分配机构');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G5','查看','查看社区列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G6','分配租户','为社区分配数据库租户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G7','分配站点','为社区分配站点');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J1','创建','创建租户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J2','编辑','编辑租户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J3','删除','删除租户');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J4','查看','查看租户列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K1','创建','创建站点');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K2','编辑','编辑站点');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K3','删除','删除站点');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K4','查看','查看站点列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K5','分配社区','为站点分配社区');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K6','操作','对站点进行启动/停止/测试连接操作');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L1','发送消息','发送消息');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L2','查看','查看消息列表');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L3','设置','设置定时发送消息');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L4','删除','删除消息');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M1','创建','创建数据字典');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M2','编辑','编辑数据字典');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M3','删除','删除数据字典');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M4','查看','查看数据字典');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N1','创建','创建业务类型');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N2','编辑','编辑业务类型');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N3','删除','删除业务类型');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N4','查看','查看业务类型');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N5','设置','设置业务材料');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'O1','社区级','社区管理员既可以管社区也可以管机构');
INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'O2','机构级','机构管理员只允许管机构');


--创建角色
INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('系统管理员', '系统默认');	--1
INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('前台', '自定义');       	--2
INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('质检', '自定义');       	--3
INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('审档', '自定义');       	--4
INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('查询', '自定义');       	--5
INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('上架下架', '自定义');       --6

--为用户分配角色
INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(1,1); --为system用设置角色
INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(2,2); --为前台用户设置前台角色
INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(3,3); --为质检用户设置质检角色
INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(4,4); --为审档用户设置审档角色
INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(5,5); --为查询用户设置查询数据角色
INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(6,6); --为查询用户设置查询数据角色

--为角色设置权限
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,1);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,2);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,3);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,4);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,5);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,6);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,7);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,8);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,9);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,10);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,11);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,12);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,13);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,14);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,15);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,16);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,17);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,18);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,19);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,20);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,21);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,22);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,23);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,24);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,25);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,26);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,27);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,28);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,29);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,30);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,31);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,32);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,33);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,34);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,35);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,36);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,37);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,38);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,39);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,40);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,41);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,42);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,43);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,44);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,45);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,46);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,47);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,48);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,49);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,50);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,51);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,52);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,53);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,54);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,55);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,56);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,57);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,58);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,59);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,60);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,61);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(2, 2); 
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(3, 3);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(4, 4);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(5, 5);
INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(6, 6);

--业务类型
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('注册登记', 0,'二级','0001');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('转移登记', 0,'二级','0003');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('抵押登记', 0,'二级','0004');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('解除抵押登记', 0,'二级','0005');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('质押备案', 0,'二级','0006');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('解除质押备案', 0,'二级','0007');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('补领登记证书', 0,'二级','0008');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('换领登记证书', 0,'二级','0009');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('申领登记证书', 0,'二级','0010');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('登记事项更正', 0,'二级','0011');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('补建机动车档案', 0,'二级','0012');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('转入机动车', 0,'二级','0013');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('影像化档案信息更正', 0,'二级','0014');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('变更机动车所有人姓名/名称', 0,'二级','0021');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('变更共同所有人姓名/名称', 0,'二级','0022');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('变更使用性质', 0,'二级','0023');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('更换发动机', 0,'二级','0024');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('更换车身/车架', 0,'二级','0025');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('变更车身颜色', 0,'二级','0026');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('更换整车', 0,'二级','0027');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('住所迁出车管所管辖区域', 0,'二级','0028');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('重新打刻发动机号码', 0,'二级','0029');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('转出/注销恢复', 0,'二级','0031');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('重新打刻车辆识别', 0,'二级','0210');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('变更身份证明名称/号码', 0,'二级','0211');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('加装残疾人操纵辅助装备', 0,'二级','0214');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('拆除残疾人操纵辅助装置', 0,'二级','0215');
INSERT INTO BUSINESS(NAME,NEEDTOCHECK,CHECKLEVEL,CODE) VALUES('变更登记', 0,'二级','0216');

--数据字典
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'1-大型汽车','A001');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'2-小型汽车','A002');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'《机动车注册、转移、注销登记转入申请表》原件','B001');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车所有人身份证明复印件','B002');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车查验记录表原件','B003');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'车辆购置税完税证明副联原件','B004');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车的来历证明原件或复印件','B005');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'合格证','B006');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'进口车5部位照片','B007');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车变更登记备案申请表','B008');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'变更证明','B009');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'行驶证原件','B010');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车变更登记备案申请表','B011');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'变更前机动车所有人身份证明','B012');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'共同所有的公证证明或证明夫妻关系的居民户口簿和结婚证','B013');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车查验记录表原件','B014');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'变更使用性质证明','B015');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车安全技术检验合格证明','B016');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'行驶证原件','B017');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'技术鉴定证明或公安机关发还证明','B018');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'现合格证','B019');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'原合格证','B020');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'行驶证原件','B021');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'技术鉴定证明或公安机关发还证明','B022');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'操纵辅助装置加装合格证明','B023');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'安全技术检验合格证明','B024');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'《机动车注册、转移、注销登记转入申请表》原件','B025');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'现机动车所有人身份证明','B026');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'原机动车所有人身份证明','B027');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车所有权转移证明','B028');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车抵押登记或者质押备案申请表','B029');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'抵押权人身份证明','B030');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'抵押合同','B031');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车抵押登记或者质押备案申请表','B032');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'抵押权人身份证明','B033');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》','B034');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'典当行身份证明','B035');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车抵押登记或者质押备案申请表','B036');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'典当行身份证明','B037');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》','B038');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'人民检察院、行政执法部门未得到登记证书证明','B039');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车勘误登记申请表','B040');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'书面报告','B041');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'批准补建机动车档案文件','B042');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'该机动车在系统中的所有记录信息','B043');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'核对公函','B044');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'《机动车注册、转移、注销登记转入申请表》原件','B045');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'机动车档案资料','B046');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'影像化档案信息更正申请表','B047');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'申请表','B048');
INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'转出注销相关资料','B049');

--业务材料关系
INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'B001');
INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'B002');
INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'B003');
INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'B004');
INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'B005');
INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'B006');
INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'B007');
 

--机构-业务
INSERT INTO COMPANYBUSINESSES(COMPANYUNIQUEID, BUSINESSUNIQUEID) VALUES(2, 1);
--INSERT INTO COMPANYBUSINESSES(COMPANYUNIQUEID, BUSINESSUNIQUEID) VALUES(2, 2);

--创建站点
INSERT INTO SITE(SITENAME,SITETYPE,HOSTADDR,PORT,DEFAULTREMOTEDIRECTORY,USERNAME,PASSWORD,MODE,CHARSET,RUNNINGSTATUS,CODE) VALUES('我的站点123','FTP','127.0.0.1',21,'/','user1','123456','主动','UTF-8',0,'AAAA');
INSERT INTO SITE(SITENAME,SITETYPE,HOSTADDR,PORT,DEFAULTREMOTEDIRECTORY,USERNAME,PASSWORD,MODE,CHARSET,RUNNINGSTATUS,CODE) VALUES('公司站点','FTP','10.48.5.75',21,'/','chens','Wonderful2018','主动','UTF-8',0,'BBBB');
INSERT INTO SITE(SITENAME,SITETYPE,HOSTADDR,PORT,DEFAULTREMOTEDIRECTORY,USERNAME,PASSWORD,MODE,CHARSET,RUNNINGSTATUS,CODE) VALUES('C盘','File','C:\Demo\tb4',21,'/','','','主动','UTF-8',1,'CCCC');
--站点容量
INSERT INTO SITECAPACITY(SITEUNIQUEID,CAPACITY,USEDSPACE,UPDATETIMEMILLIS,UNIT,UNITNUMBER,MAXBATCH,MAXBUSINESS) VALUES(1, 20000000000, 0, 0,'GB','1', 1000, 5000);
INSERT INTO SITECAPACITY(SITEUNIQUEID,CAPACITY,USEDSPACE,UPDATETIMEMILLIS,UNIT,UNITNUMBER,MAXBATCH,MAXBUSINESS) VALUES(2, 20000000000, 0, 0,'MB','300', 1000, 5000);
INSERT INTO SITECAPACITY(SITEUNIQUEID,CAPACITY,USEDSPACE,UPDATETIMEMILLIS,UNIT,UNITNUMBER,MAXBATCH,MAXBUSINESS) VALUES(3, 20000000000, 0, 0,'GB','20', 1000, 5000);
--站点允许最大文件夹数
INSERT INTO SITEFOLDER(SITEUNIQUEID,BATCHCOUNT,BUSINESSCOUNT) VALUES(1,1,0);
INSERT INTO SITEFOLDER(SITEUNIQUEID,BATCHCOUNT,BUSINESSCOUNT) VALUES(2,1,0);
INSERT INTO SITEFOLDER(SITEUNIQUEID,BATCHCOUNT,BUSINESSCOUNT) VALUES(3,1,0);

--社区站点
INSERT INTO COMMUNITYSITES(COMMUNITYUNIQUEID, SITEUNIQUEID) VALUES(2,3);


---- 社区
--INSERT INTO COMMUNITYS(COMMUNITYNAME, COMMUNITYDESCRIPTION, COMPANYUNIQUEID) VALUES('大连市内四区','市内四区范围内业务办理', 0);
--
---- 库房
--INSERT INTO STOREHOUSE(NAME,DESCRIPTION,STATUS,CODE) VALUES('库房123', '中山档案库房', 0, '001');

INSERT INTO TENANTS(TENANTNAME) VALUES ('中山区');
INSERT INTO TENANTS(TENANTNAME) VALUES ('长海县');
   
  RETURN;
END
$BODY$
LANGUAGE plpgsql$$

SELECT * FROM insert_data()$$

