DROP FUNCTION IF EXISTS INSERT_DATA();
CREATE OR REPLACE FUNCTION INSERT_DATA() RETURNS SETOF integer AS
$BODY$
BEGIN
    --插入系统用户
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('system','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'',0,0,'sys1@max.com','047-5831-01',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (1,'系统管理员','img/adminmenu/users/user1.png',5,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','车','管');
	
	
	--插入系统权限类别
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('登录类别');--A
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('个人配置');--B
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理用户');--C
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理角色');--D	
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理权限');--E
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理机构');--F
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理社区');--G
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理租户');--J
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理站点');--K
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('广播消息');--L
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('数据字典');--M
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('业务类型');--N
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理范围');--O
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理库房');--P
	
	--插入所有权限
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A1','管理员','管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A2','前台','前台用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A3','质检','质检用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A4','审档','审档用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A5','查询','数据查询用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A6','上架下架','上架下架用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A7','确认审档','只对一级审档业务确认审档');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A8','影像化管理员','影像化管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A9','影像化录入','影像化录入');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A10','影像化质检','影像化质检');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B1','更改个人资料','更改个人资料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B2','更改密码','更改密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C1','创建','创建用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C2','编辑','编辑用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C3','删除','删除用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C4','查看','查看用户列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C5','分配角色','为用户分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C6','分配业务','为用户分配业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C7','重置密码','为用户重置密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D1','创建','创建角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D2','编辑','编辑角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D3','删除','删除角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D4','分配用户','为角色分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D5','设置权限','为角色分配权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D6','查看','查看角色列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E1','分配角色','为权限分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E2','编辑','编辑权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E3','查看','查看权限列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F1','创建','创建机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F2','编辑','编辑机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F3','删除','删除机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F4','分配用户','为机构分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F5','管理库房','管理库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F6','查看','查看机构列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F7','设置','设置业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G1','创建','创建社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G2','编辑','编辑社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G3','删除','删除社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G4','分配机构','分配机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G5','查看','查看社区列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G6','分配租户','为社区分配数据库租户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G7','分配站点','为社区分配站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J1','创建','创建租户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J2','编辑','编辑租户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J3','删除','删除租户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J4','查看','查看租户列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'J5','分配社区','为租户分配一个社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K1','创建','创建站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K2','编辑','编辑站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K3','删除','删除站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K4','查看','查看站点列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K5','分配社区','为站点分配社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'K6','操作','对站点进行启动/停止/测试连接操作');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L1','发送消息','发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L2','查看','查看消息列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L3','设置','设置定时发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'L4','删除','删除消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M1','创建','创建数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M2','编辑','编辑数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M3','删除','删除数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'M4','查看','查看数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N1','创建','创建业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N2','编辑','编辑业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N3','删除','删除业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N4','查看','查看业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'N5','设置','设置业务材料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'O1','社区范围内','社区管理员既可以管社区也可以管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'O2','机构范围内','机构管理员只允许管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'P1','创建','创建库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'P2','编辑','编辑库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'P3','删除','删除库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'P4','查看','查看库房列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'P5','分配机构','为库房分配一个机构（通常机构是车管所）');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'P6','管理密集架','管理密集架');
	
	--插入全部角色
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('系统管理员', '系统内置');	--1
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('前台', '自定义');	--2
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('质检', '自定义');	--3
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('审档', '自定义');	--4
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('查询', '自定义');	--5
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('上架下架', '自定义');	--6
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('确认审档', '自定义');	--7
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化管理员', '自定义');	--8
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化录入', '自定义');	--9
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化质检', '自定义');	--10
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('二手车管理员', '自定义');	--11

	
	--插入系统管理员权限
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,11);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,12);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,13);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,14);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,15);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,16);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,17);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,18);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,19);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,20);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,21);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,22);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,23);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,24);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,25);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,26);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,27);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,28);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,29);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,30);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,31);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,32);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,33);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,34);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,35);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,36);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,37);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,38);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,39);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,40);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,41);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,42);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,43);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,44);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,45);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,46);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,47);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,48);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,49);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,50);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,51);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,52);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,53);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,54);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,55);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,56);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,57);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,58);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,59);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,60);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,61);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,62);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,65);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,66);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,67);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,68);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,69);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,70);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,71);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,72);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,73);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,74);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(2,2);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(3,3);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(4,4);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(5,5);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(6,6);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(7,7);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(8,8);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(9,9);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(10,10);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(11,1);
	
	--插入system用户角色关系
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(1,1); --为system用设置角色
	
	--插入业务类型
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('注册登记','','0001');--1
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转移登记','','0003');--2
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('抵押登记','一级审档','0004');--3
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解除抵押登记','二级审档','0005');--4
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('质押备案','二级审档','0006');--5
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解除质押备案','二级审档','0007');--6
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补领登记证书','二级审档','0008');--7
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('换领登记证书','二级审档','0009');--8
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('申领登记证书','二级审档','0010');--9
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('登记事项更正','二级审档','0011');--10
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补建机动车档案','二级审档','0012');--11
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转入机动车','二级审档','0013');--12
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('影像化档案信息更正','二级审档','0014');--13
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更机动车所有人姓名/名称','二级审档','0021');--14
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更共同所有人姓名/名称','二级审档','0022');--15
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更使用性质','二级审档','0023');--16
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换发动机','二级审档','0024');--17
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换车身/车架','二级审档','0025');--18
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更车身颜色','二级审档','0026');--19
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换整车','二级审档','0027');--19
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('住所迁出车管所管辖区域','二级审档','0028');--20
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('重新打刻发动机号码','二级审档','0029');--21
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转出/注销恢复','二级审档','0031');--22
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('重新打刻车辆识别','二级审档','0210');--23
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更身份证明名称/号码','二级审档','0211');--24
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('加装残疾人操纵辅助装备','二级审档','0214');--25
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('拆除残疾人操纵辅助装置','二级审档','0215');--26
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记','二级审档','0216');--27
	
	----数据字典
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'1-大型汽车','A001');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'2-小型汽车','A002');--type1:号牌种类
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'辽宁省','210000');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'大连市','210200');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'中山区','210202');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'西岗区','210203');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'沙河口区','210204');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'甘井子区','210211');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'旅顺口区','210212');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'金州区','210213');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'长海县','210224');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'瓦房店市','210281');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'普兰店区','210282');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'庄河市','210283');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注册、转移、注销登记转入申请表》原件','A001'); --type3:代表业务材料自己弄
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有人身份证明复印件','A002');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车查验记录表原件','A003');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆购置税完税证明副联原件','A004');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车的来历证明原件或复印件','A005');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'合格证','A006');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进口车5部位照片','A007');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车变更登记备案申请表','A008');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更证明','A009');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更前机动车所有人身份证明','A010');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'共同所有的公证证明或证明夫妻关系的居民户口簿和结婚证','A011');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更使用性质证明','A012');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车安全技术检验合格证明','A013');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术鉴定证明或公安机关发还证明','A014');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现合格证','A015');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原合格证','A016');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行驶证原件','A017');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'操纵辅助装置加装合格证明','A018');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'安全技术检验合格证明','A019');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现机动车所有人身份证明','A020');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车所有人身份证明','A021');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有权转移证明','A022');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车抵押登记或者质押备案申请表','A023');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押权人身份证明','A024');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押合同','A025');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》','A026');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明','A027');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明','A028');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民检察院、行政执法部门未得到登记证书证明','A029');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车勘误登记申请表','A030');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'书面报告','A031');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准补建机动车档案文件','A032');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'该机动车在系统中的所有记录信息','A033');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'核对公函','A034');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料','A035');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'影像化档案信息更正申请表','A036');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'申请表','A037');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'转出注销相关资料','A038');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其他资料','A039');
	
	----插入业务材料关系
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A001');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A004');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A005');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A006');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A007');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A009');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A010');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A011');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A012');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A012');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A039');
	
	----插入社区
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('辽宁省', '辽宁省社区', 1, 1);
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('大连市', '大连市社区', 1, 2);
	
	----插入机构
    INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (0,'大连市车管所','210000','210200','210202','20高中',1,NULL,0,'车管所');
 	INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (0,'大连市二手车市场','210000','210200','210211','20高中',0,NULL,1,'二手车');
    
    
  RETURN;
END
$BODY$
LANGUAGE plpgsql$$

SELECT * FROM INSERT_DATA()$$	

