--消息系统
DELETE FROM MESSAGES;
DELETE FROM MESSAGERECIPIENT;
DELETE FROM REMINDERFREQUENCY;
DELETE FROM COMMUNITYSITES;
DELETE FROM COMMUNITYTENANTS;
DELETE FROM TENANTS;
DELETE FROM COMPANYBUSINESSES;
DELETE FROM BUSINESSITEMS;
DELETE FROM DATADICTIONARY;
 
DELETE FROM COMMUNITIES;
DELETE FROM COMPANIES;
DELETE FROM COMMUNITIES;
DELETE FROM ROLERIGHT;
DELETE FROM ROLEMEMBER;
DELETE FROM ROLE;
DELETE FROM USERPROFILES;
DELETE FROM PERMISSIONCATEGORY;
DELETE FROM PERMISSION;
DELETE FROM BUSINESS;
DELETE FROM SITECAPACITY;
DELETE FROM SITE;
 
 
DELETE FROM QUEUE_1;
DELETE FROM QUEUE_2;
DELETE FROM USERS;
DELETE FROM PORTFOLIO;
DELETE FROM FILEBOX;
DELETE FROM DENSEFRAME;
DELETE FROM STOREHOUSE;


DROP TABLE MESSAGES IF EXISTS;
DROP TABLE MESSAGERECIPIENT IF EXISTS;
DROP TABLE REMINDERFREQUENCY IF EXISTS;
DROP TABLE COMMUNITYSITES IF EXISTS;
DROP TABLE COMMUNITYTENANTS IF EXISTS;
DROP TABLE TENANTS IF EXISTS;
DROP TABLE COMPANYBUSINESSES IF EXISTS;
DROP TABLE BUSINESSITEMS IF EXISTS;
DROP TABLE DATAITEMS IF EXISTS;
DROP TABLE AUDITS IF EXISTS;
DROP TABLE QUEUE_2 IF EXISTS;
DROP TABLE QUEUE_1 IF EXISTS;
DROP TABLE REMINDER IF EXISTS;
DROP TABLE DOCUMENTS_2 IF EXISTS; 
DROP TABLE DOCUMENTS_1 IF EXISTS; 
DROP TABLE TRANSACTION IF EXISTS; 
DROP TABLE USERSITE IF EXISTS;
DROP TABLE SITECAPACITY IF EXISTS;
DROP TABLE SITE IF EXISTS;
DROP TABLE BUSINESS IF EXISTS; 
DROP TABLE ROLERIGHT IF EXISTS;
DROP TABLE ROLEMEMBER IF EXISTS;
DROP TABLE PERMISSIONCATEGORY IF EXISTS;
DROP TABLE PERMISSION IF EXISTS;
DROP TABLE ROLE IF EXISTS;
DROP TABLE USERPROFILES IF EXISTS;
DROP TABLE USERS IF EXISTS;
DROP TABLE PORTFOLIO IF EXISTS;
DROP TABLE FILEBOX IF EXISTS;
DROP TABLE DENSEFRAME IF EXISTS;
DROP TABLE STOREHOUSE IF EXISTS;
DROP TABLE COMPANIES IF EXISTS;
DROP TABLE COMMUNITIES IF EXISTS;


--社区
CREATE TABLE COMMUNITIES (
	COMMUNITYUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	COMMUNITYNAME VARCHAR(20) NOT NULL,
	COMMUNITYDESCRIPTION VARCHAR(60),
	GROUPID INT NOT NULL,
	LEVEL INT NOT NULL
);

--机构
CREATE TABLE COMPANIES (
	COMPANYUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYNAME VARCHAR(20) NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL, -- 省
	CITY VARCHAR(20),  --市
	PREFECTURE VARCHAR(20), --县
	DISTRICT VARCHAR(20), --区
	ADDRESS VARCHAR(60),
	HASSTOREHOUSE INT NOT NULL, -- 1存在库房，0不存在库房
	STOREHOUSEUNIQUEID INT,
	IGNORECHECKER INT NOT NULL -- 1-忽略质检（前台可以直接提交到审档队列），0-不忽略
);

--用户表
CREATE TABLE USERS (
	USERUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	HASHED VARCHAR(60) NOT NULL,
	ACTIVATED INT NOT NULL,
	COMPANYNAME VARCHAR(20),
	COMPANYUNIQUEID INT,
	COMMUNITYUNIQUEID INT,
	EMAIL VARCHAR(20),
	PHONE VARCHAR(20),
	FAX VARCHAR(20)
);

--用户配置文件
CREATE TABLE USERPROFILES (
	USERPROFILEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	TITLE VARCHAR(20),
	PICTURE VARCHAR(40),
	MANAGERUNIQUEID INT,
	CREATEDBY VARCHAR(20),
	CREATORUNIQUEID INT NOT NULL,
	DATECREATED TIMESTAMP,
	DATELASTMODIFIED TIMESTAMP,
	LASTLOGON TIMESTAMP,
	SEX VARCHAR(4),
	EMAIL VARCHAR(20),
	LOCATION VARCHAR(120),
	PHONE VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20)
);

--业务类型
CREATE TABLE BUSINESS (
	BUSINESSUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	FILECHECK INT NOT NULL,
	HASFIRSTINDEX INT NOT NULL, --1代表这个业务的业务索引号是从1开始的，--0则根据其他业务累加
	LOCALCHECK INT NOT NULL  -- 是否用本机构内审档员审档， 1-是 0 否
);

--数据字典
CREATE TABLE DATAITEMS (
	DATAITEMUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	CATEGORYNAME VARCHAR(20) NOT NULL,
	ITEMNAME VARCHAR(20) NOT NULL
);

--业务类型-数据字典
CREATE TABLE BUSINESSITEMS (
	ITEMUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	BUSINESSUNIQUEID INT NOT NULL,
	DATAITEMUNIQUEID INT NOT NULL
);

--机构-业务类型
CREATE TABLE COMPANYBUSINESSES (
	CBUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	COMPANYUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--库房
CREATE TABLE STOREHOUSE (
	STOREHOUSEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	CODE VARCHAR(20) NOT NULL
);
--密集架
CREATE TABLE DENSEFRAME (
	DENSEFRAMEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	STOREHOUSEUNIQUEID INT NOT NULL,
	ROWCOUNT INT NOT NULL,
	COLUMNCOUNT INT NOT NULL,
	CODE VARCHAR(20) NOT NULL
);
--文件盒
CREATE TABLE FILEBOX (
	FILEBOXUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	DENSEFRAMEUNIQUEID INT NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	ROW INT NOT NULL,
	COL INT NOT NULL
);
--档案袋
CREATE TABLE PORTFOLIO (
	PORTFOLIOUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	FILEBOXUNIQUEID INT NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	VIN VARCHAR(50)
);
--租户
CREATE TABLE TENANTS (
	TENANTUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	TENANTNAME VARCHAR(20) NOT NULL
);
--社区-租户
CREATE TABLE COMMUNITYTENANTS (
	CTUNIQUEID INT AUTO_INCREMENT NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	TENANTUNIQUEID INT NOT NULL,
	FOREIGN KEY(COMMUNITYUNIQUEID) REFERENCES COMMUNITIES(COMMUNITYUNIQUEID),
	FOREIGN KEY(TENANTUNIQUEID) REFERENCES TENANTS(TENANTUNIQUEID),
	PRIMARY KEY(CTUNIQUEID, COMMUNITYUNIQUEID, TENANTUNIQUEID)
);
--站点
CREATE TABLE SITE (
	SITEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	SITENAME VARCHAR(20) NOT NULL,
	SITETYPE VARCHAR(20) NOT NULL,
	HOSTADDR VARCHAR(50) NOT NULL,
	PORT INT,
	DEFAULTREMOTEDIRECTORY VARCHAR(50),
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(50),
	MODE VARCHAR(10),
	CHARSET VARCHAR(10),
	RUNNINGSTATUS INT NOT NULL
);

--站点容量
CREATE TABLE SITECAPACITY (
	SITECAPACITYUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	SITEUNIQUEID INT,
	CAPACITY BIGINT,
	USEDSPACE BIGINT,
	UPDATETIMEMILLIS BIGINT,
	UNIT VARCHAR(4),
	UNITNUMBER VARCHAR(10)
);

--社区-站点
CREATE TABLE COMMUNITYSITES (
	CSUNIQUEID INT AUTO_INCREMENT NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	FOREIGN KEY (COMMUNITYUNIQUEID)
		REFERENCES COMMUNITIES (COMMUNITYUNIQUEID),
	FOREIGN KEY (SITEUNIQUEID)
		REFERENCES SITE (SITEUNIQUEID),
	PRIMARY KEY (CSUNIQUEID, COMMUNITYUNIQUEID, SITEUNIQUEID)
);
--消息系统
CREATE TABLE MESSAGES (
	MESSAGEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	SUBJECT VARCHAR(50) NOT NULL,
	CREATORUNIQUEID INT NOT NULL,
	MESSAGEBODY VARCHAR(200) NOT NULL,
	DATECREATED TIMESTAMP,
	PARENTMESSAGEUNIQUEID INT NOT NULL,
	EXPIRYDATE TIMESTAMP,
	REMINDER INT NOT NULL,---是否需要提醒1-提醒,0-不提醒
	NEXTREMINDDATE TIMESTAMP,
	REMINDERFREQUENCYID INT NOT NULL,
	RECIPIENTNAME VARCHAR(20) NOT NULL --接收者名称
);
--消息接收者
CREATE TABLE MESSAGERECIPIENT (
	UNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL,
	COMPANYUNIQUEID INT NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	MESSAGEUNIQUEID INT NOT NULL,
	READ INT NOT NULL,
	VIEWNAME VARCHAR(20)
);
--提醒频率
CREATE TABLE REMINDERFREQUENCY (
	FREQUENCYUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(20),
	FREQUENCY INT NOT NULL, -- daily=1, weekly=7,
	ACTIVE INT NOT NULL
);
--事务
CREATE TABLE TRANSACTION (
	TRANSACTIONUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	BARCODE VARCHAR(50) NOT NULL,
	PLATETYPE VARCHAR(20) NOT NULL,
	PLATENUMBER VARCHAR(20) NOT NULL,
	VIN VARCHAR(50) NOT NULL,
	DATECREATED TIMESTAMP NOT NULL,
	DATEMODIFIED TIMESTAMP,
	DATEFINISHED TIMESTAMP,
	STATUS VARCHAR(20) NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYUNIQUEID INT NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL,
	CITY VARCHAR(20) NOT NULL,
	PREFECTURE VARCHAR(20),
	DISTRICT VARCHAR(20),
	UUID VARCHAR(36) NOT NULL,
	CODE VARCHAR(15),--上架号
	TYPIST INT NOT NULL, --录入员
	INDEXNUMBER INT NOT NULL --业务顺序号
);
--主要材料
CREATE TABLE DOCUMENTS_1 (
	DOCUMENTUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY INT
);
--次要材料
CREATE TABLE DOCUMENTS_2 (
	DOCUMENTUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY INT
);
--质检队列
CREATE TABLE QUEUE_1 (
	QUEUEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	LOCKEDBYUSER INT,
	SENTBYUSER INT,
	COMMUNITYUNIQUEID INT NOT NULL
);
--审档队列
CREATE TABLE QUEUE_2 (
	QUEUEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	LOCKEDBYUSER INT,
	SENTBYUSER INT,
	COMMUNITYUNIQUEID INT NOT NULL
);

--角色表
CREATE TABLE ROLE (
	ROLEUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	ROLENAME VARCHAR(20) NOT NULL,
	ROLETYPE VARCHAR(10) NOT NULL
);
--权限表
CREATE TABLE PERMISSION (
	PERMISSIONUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	CATEGORYUNIQUEID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);
--权限类别表
CREATE TABLE PERMISSIONCATEGORY (
	CATEGORYUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL
);
--用户与角色关系表
CREATE TABLE ROLEMEMBER (
	ROLEMEMBERUNIQUEID INT AUTO_INCREMENT NOT NULL,
	USERUNIQUEID INT NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	FOREIGN KEY (USERUNIQUEID)
		REFERENCES USERS (USERUNIQUEID),
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	PRIMARY KEY (ROLEMEMBERUNIQUEID, USERUNIQUEID, ROLEUNIQUEID)
);
--角色与权限关系表
CREATE TABLE ROLERIGHT (
	ROLERIGHTUNIQUEID INT AUTO_INCREMENT NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	PERMISSIONUNIQUEID INT NOT NULL,
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	FOREIGN KEY (PERMISSIONUNIQUEID)
		REFERENCES PERMISSION (PERMISSIONUNIQUEID),
	PRIMARY KEY (ROLERIGHTUNIQUEID, ROLEUNIQUEID, PERMISSIONUNIQUEID)
);

--审批记录
CREATE TABLE AUDITS (
	AUDITUNIQUEID INT AUTO_INCREMENT PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	AUDITOR INT NOT NULL,--审核人
	AUDITRESULTS VARCHAR(160),
	AUDITDATE TIMESTAMP NOT NULL
);
