--消息系统
DELETE FROM MESSAGES;
DELETE FROM MESSAGERECIPIENT;
DELETE FROM REMINDERFREQUENCY;
DELETE FROM SENDDETAILS;
DELETE FROM COMMUNITYSITES;
DELETE FROM COMMUNITYTENANTS;
DELETE FROM TENANTS;
DELETE FROM COMPANYBUSINESSES;
DELETE FROM BUSINESSITEMS;
DELETE FROM DATAITEMS;
DELETE FROM AUDITS;
DELETE FROM COMMUNITIES;
DELETE FROM COMPANIES;
DELETE FROM COMMUNITIES;
DELETE FROM ROLERIGHT;
DELETE FROM ROLEMEMBER;
DELETE FROM ROLE;
DELETE FROM USERPROFILES;
DELETE FROM PERMISSIONCATEGORY;
DELETE FROM PERMISSION;
DELETE FROM BUSINESS;
DELETE FROM SITECAPACITY;
DELETE FROM SITE;
DELETE FROM TRANSACTION;
DELETE FROM DOCUMENTS_1;
DELETE FROM DOCUMENTS_2;
DELETE FROM REMINDER;
DELETE FROM QUEUE_1;
DELETE FROM QUEUE_2;
DELETE FROM USERS;
DELETE FROM PORTFOLIO;
DELETE FROM FILEBOX;
DELETE FROM DENSEFRAME;
DELETE FROM STOREHOUSE;


DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS MESSAGERECIPIENT;
DROP TABLE IF EXISTS REMINDERFREQUENCY;
DROP TABLE IF EXISTS SENDDETAILS;
DROP TABLE IF EXISTS COMMUNITYSITES;
DROP TABLE IF EXISTS COMMUNITYTENANTS;
DROP TABLE IF EXISTS TENANTS;
DROP TABLE IF EXISTS COMPANYBUSINESSES;
DROP TABLE IF EXISTS BUSINESSITEMS;
DROP TABLE IF EXISTS DATAITEMS;
DROP TABLE IF EXISTS AUDITS;
DROP TABLE IF EXISTS QUEUE_2;
DROP TABLE IF EXISTS QUEUE_1;
DROP TABLE IF EXISTS REMINDER;
DROP TABLE IF EXISTS DOCUMENTS_2; 
DROP TABLE IF EXISTS DOCUMENTS_1; 
DROP TABLE IF EXISTS TRANSACTION; 
DROP TABLE IF EXISTS USERSITE;
DROP TABLE IF EXISTS SITECAPACITY;
DROP TABLE IF EXISTS SITE;
DROP TABLE IF EXISTS BUSINESS; 
DROP TABLE IF EXISTS ROLERIGHT;
DROP TABLE IF EXISTS ROLEMEMBER;
DROP TABLE IF EXISTS PERMISSIONCATEGORY;
DROP TABLE IF EXISTS PERMISSION;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USERPROFILES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PORTFOLIO;
DROP TABLE IF EXISTS FILEBOX;
DROP TABLE IF EXISTS DENSEFRAME;
DROP TABLE IF EXISTS STOREHOUSE;
DROP TABLE IF EXISTS COMPANIES;
DROP TABLE IF EXISTS COMMUNITIES;

--社区
CREATE TABLE COMMUNITIES (
	COMMUNITYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYNAME VARCHAR(20) NOT NULL,
	COMMUNITYDESCRIPTION VARCHAR(60),
	GROUPID INT NOT NULL,
	LEVEL SMALLINT NOT NULL
);

--机构
CREATE TABLE COMPANIES (
	COMPANYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYNAME VARCHAR(20) NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL, -- 省
	CITY VARCHAR(20),  --市
	PREFECTURE VARCHAR(20), --县
	DISTRICT VARCHAR(20), --区
	ADDRESS VARCHAR(60),
	CANCREATESTOREHOUSE SMALLINT NOT NULL, -- 1可以创建库房，0不可以创建库房
	STOREHOUSEUNIQUEID INT,
	IGNORECHECKER SMALLINT NOT NULL -- 1-忽略质检（前台可以直接提交到审档队列），0-不忽略
);

--用户表
CREATE TABLE USERS (
	USERUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	HASHED VARCHAR(60) NOT NULL,
	ACTIVATED SMALLINT NOT NULL,
	COMPANYNAME VARCHAR(20),
	COMPANYUNIQUEID INT,
	COMMUNITYUNIQUEID INT,
	EMAIL VARCHAR(20),
	PHONE VARCHAR(20),
	FAX VARCHAR(20)
);

--用户配置文件
CREATE TABLE USERPROFILES (
	USERPROFILEUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	TITLE VARCHAR(20),
	PICTURE VARCHAR(40),
	MANAGERUNIQUEID INT,
	CREATEDBY VARCHAR(20),
	CREATORUNIQUEID INT NOT NULL,
	DATECREATED TIMESTAMP,
	DATELASTMODIFIED TIMESTAMP,
	LASTLOGON TIMESTAMP,
	SEX VARCHAR(4),
	EMAIL VARCHAR(20),
	LOCATION VARCHAR(120),
	PHONE VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20)
);

--业务类型
CREATE TABLE BUSINESS (
	BUSINESSUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	FILECHECK SMALLINT NOT NULL,
	HASFIRSTINDEX SMALLINT NOT NULL, --1代表这个业务的业务索引号是从1开始的，--0则根据其他业务累加
	LOCALCHECK SMALLINT NOT NULL  -- 是否用本机构内审档员审档， 1-是 0 否
);

--数据字典
CREATE TABLE DATAITEMS (
	DATAITEMUNIQUEID SERIAL PRIMARY KEY,
	CATEGORYNAME VARCHAR(20) NOT NULL,
	ITEMNAME VARCHAR(20) NOT NULL
);

--业务类型-数据字典
CREATE TABLE BUSINESSITEMS (
	ITEMUNIQUEID SERIAL PRIMARY KEY,
	BUSINESSUNIQUEID INT NOT NULL,
	DATAITEMUNIQUEID INT NOT NULL
);

--机构-业务类型
CREATE TABLE COMPANYBUSINESSES (
	CBUNIQUEID SERIAL PRIMARY KEY,
	COMPANYUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--库房
CREATE TABLE STOREHOUSE (
	STOREHOUSEUNIQUEID SERIAL PRIMARY KEY,
	CODE VARCHAR(20) NOT NULL
);
--密集架
CREATE TABLE DENSEFRAME (
	DENSEFRAMEUNIQUEID SERIAL PRIMARY KEY,
	STOREHOUSEUNIQUEID INT NOT NULL,
	ROWCOUNT SMALLINT NOT NULL,
	COLUMNCOUNT SMALLINT NOT NULL,
	CODE VARCHAR(20) NOT NULL
);
--文件盒
CREATE TABLE FILEBOX (
	FILEBOXUNIQUEID SERIAL PRIMARY KEY,
	DENSEFRAMEUNIQUEID INT NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	ROW SMALLINT NOT NULL,
	COL SMALLINT NOT NULL
);
--档案袋
CREATE TABLE PORTFOLIO (
	PORTFOLIOUNIQUEID SERIAL PRIMARY KEY,
	FILEBOXUNIQUEID INT NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	VIN VARCHAR(50)
);
--租户
CREATE TABLE TENANTS (
	TENANTUNIQUEID SERIAL PRIMARY KEY,
	TENANTNAME VARCHAR(20) NOT NULL
);
--社区-租户
CREATE TABLE COMMUNITYTENANTS (
	CTUNIQUEID SERIAL NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	TENANTUNIQUEID INT NOT NULL,
	FOREIGN KEY(COMMUNITYUNIQUEID) REFERENCES COMMUNITIES(COMMUNITYUNIQUEID),
	FOREIGN KEY(TENANTUNIQUEID) REFERENCES TENANTS(TENANTUNIQUEID),
	PRIMARY KEY(CTUNIQUEID, COMMUNITYUNIQUEID, TENANTUNIQUEID)
);
--站点
CREATE TABLE SITE (
	SITEUNIQUEID SERIAL PRIMARY KEY,
	SITENAME VARCHAR(20) NOT NULL,
	SITETYPE VARCHAR(20) NOT NULL,
	HOSTADDR VARCHAR(50) NOT NULL,
	PORT SMALLINT,
	DEFAULTREMOTEDIRECTORY VARCHAR(50),
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(50),
	MODE VARCHAR(10),
	CHARSET VARCHAR(10),
	RUNNINGSTATUS SMALLINT NOT NULL
);

--站点容量
CREATE TABLE SITECAPACITY (
	SITECAPACITYUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	CAPACITY BIGINT,
	USEDSPACE BIGINT,
	UPDATETIMEMILLIS BIGINT,
	UNIT VARCHAR(4),
	UNITNUMBER VARCHAR(10)
);

--社区-站点
CREATE TABLE COMMUNITYSITES (
	CSUNIQUEID SERIAL NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	FOREIGN KEY (COMMUNITYUNIQUEID)
		REFERENCES COMMUNITIES (COMMUNITYUNIQUEID),
	FOREIGN KEY (SITEUNIQUEID)
		REFERENCES SITE (SITEUNIQUEID),
	PRIMARY KEY (CSUNIQUEID, COMMUNITYUNIQUEID, SITEUNIQUEID)
);
--消息系统
CREATE TABLE MESSAGES (
	MESSAGEUNIQUEID SERIAL PRIMARY KEY,
	SUBJECT VARCHAR(50) NOT NULL,--标题
	MESSAGEBODY VARCHAR(200) NOT NULL,--消息体JSON
	CREATORUNIQUEID INT NOT NULL,--创建者ID
	DATECREATED TIMESTAMP, -- 创建时间
	SENTTIMES SMALLINT NOT NULL,--已发送次数
	REMINDERFREQUENCYID INT NOT NULL, -- 发送频率ID
	DELETED SMALLINT NOT NULL
);
--消息接收者
CREATE TABLE MESSAGERECIPIENT (
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收方ID
	RECIPIENTNAME VARCHAR(50) NOT NULL,--接收方名称
	RECIPIENTTYPE SMALLINT NOT NULL, --接收方类别
	MESSAGEUNIQUEID INT NOT NULL -- 消息ID
);
--提醒频率
CREATE TABLE REMINDERFREQUENCY (
	FREQUENCYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	FREQUENCY SMALLINT NOT NULL, -- 1-每天 7-每周
	ENABLED SMALLINT NOT NULL,--1-启用 0禁用
	STARTINGTIME TIMESTAMP,--起始时间
	ENDINGTIME TIMESTAMP -- 结束时间
);
--发送细节
CREATE TABLE SENDDETAILS(
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收者UserID
	MESSAGEUNIQUEID INT NOT NULL, -- 消息ID
	MARKEDASREAD SMALLINT NOT NULL, -- 标记已读
	VIEWNAME VARCHAR(20) --视图名称，如果等于空则接收方将在首个视图上显示消息
);

--事务
CREATE TABLE TRANSACTION (
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,
	BARCODE VARCHAR(50) NOT NULL,
	PLATETYPE VARCHAR(20) NOT NULL,
	PLATENUMBER VARCHAR(20) NOT NULL,
	VIN VARCHAR(50) NOT NULL,
	DATECREATED TIMESTAMP NOT NULL,
	DATEMODIFIED TIMESTAMP,
	DATEFINISHED TIMESTAMP,
	STATUS VARCHAR(20) NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYUNIQUEID INT NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL,
	CITY VARCHAR(20) NOT NULL,
	PREFECTURE VARCHAR(20),
	DISTRICT VARCHAR(20),
	UUID VARCHAR(36) NOT NULL,
	CODE VARCHAR(15),--上架号
	TYPIST INT NOT NULL, --录入员
	INDEXNUMBER INT NOT NULL --业务顺序号
);
--主要材料
CREATE TABLE DOCUMENTS_1 (
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY SMALLINT
);
--次要材料
CREATE TABLE DOCUMENTS_2 (
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY SMALLINT
);
--质检队列
CREATE TABLE QUEUE_1 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	LOCKEDBYUSER INT,
	SENTBYUSER INT,
	COMMUNITYUNIQUEID INT NOT NULL
);
--审档队列
CREATE TABLE QUEUE_2 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	LOCKEDBYUSER INT,
	SENTBYUSER INT,
	COMMUNITYUNIQUEID INT NOT NULL
);

--角色表
CREATE TABLE ROLE (
	ROLEUNIQUEID SERIAL PRIMARY KEY,
	ROLENAME VARCHAR(20) NOT NULL,
	ROLETYPE VARCHAR(10) NOT NULL
);
--权限表
CREATE TABLE PERMISSION (
	PERMISSIONUNIQUEID SERIAL PRIMARY KEY,
	CATEGORYUNIQUEID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);
--权限类别表
CREATE TABLE PERMISSIONCATEGORY (
	CATEGORYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL
);
--用户与角色关系表
CREATE TABLE ROLEMEMBER (
	ROLEMEMBERUNIQUEID SERIAL NOT NULL,
	USERUNIQUEID INT NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	FOREIGN KEY (USERUNIQUEID)
		REFERENCES USERS (USERUNIQUEID),
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	PRIMARY KEY (ROLEMEMBERUNIQUEID, USERUNIQUEID, ROLEUNIQUEID)
);
--角色与权限关系表
CREATE TABLE ROLERIGHT (
	ROLERIGHTUNIQUEID SERIAL NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	PERMISSIONUNIQUEID INT NOT NULL,
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	FOREIGN KEY (PERMISSIONUNIQUEID)
		REFERENCES PERMISSION (PERMISSIONUNIQUEID),
	PRIMARY KEY (ROLERIGHTUNIQUEID, ROLEUNIQUEID, PERMISSIONUNIQUEID)
);

--审批记录
CREATE TABLE AUDITS (
	AUDITUNIQUEID SERIAL PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	AUDITOR INT NOT NULL,--审核人
	AUDITRESULTS VARCHAR(160),
	AUDITDATE TIMESTAMP NOT NULL
);
