DROP FUNCTION IF EXISTS create_tables();
CREATE OR REPLACE FUNCTION create_tables() RETURNS SETOF integer AS
$BODY$
BEGIN

DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS MESSAGERECIPIENT;
DROP TABLE IF EXISTS REMINDERFREQUENCY;
DROP TABLE IF EXISTS SENDDETAILS;
DROP TABLE IF EXISTS COMMUNITYSITES;
DROP TABLE IF EXISTS COMMUNITYTENANTS;
DROP TABLE IF EXISTS TENANTS;
DROP TABLE IF EXISTS COMPANYBUSINESSES;
DROP TABLE IF EXISTS USERBUSINESSES;
DROP TABLE IF EXISTS BUSINESSITEMS;
DROP TABLE IF EXISTS DATADICTIONARY;
DROP TABLE IF EXISTS QUEUE_3;
DROP TABLE IF EXISTS QUEUE_2;
DROP TABLE IF EXISTS QUEUE_1;
DROP TABLE IF EXISTS SITEFOLDER;
DROP TABLE IF EXISTS SITECAPACITY;
DROP TABLE IF EXISTS SITE;
DROP TABLE IF EXISTS BUSINESS; 
DROP TABLE IF EXISTS ROLERIGHT;
DROP TABLE IF EXISTS ROLEMEMBER;
DROP TABLE IF EXISTS PERMISSIONCATEGORY;
DROP TABLE IF EXISTS PERMISSION;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USERPROFILES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FRAMENUMBER;
DROP TABLE IF EXISTS COMPANIES;
DROP TABLE IF EXISTS COMMUNITIES;

--社区
CREATE TABLE COMMUNITIES (
	COMMUNITYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYNAME VARCHAR(20) NOT NULL,
	COMMUNITYDESCRIPTION VARCHAR(60),
	GROUPID INT NOT NULL,
	LEVEL SMALLINT NOT NULL
);

--机构
CREATE TABLE COMPANIES (
	COMPANYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYNAME VARCHAR(20) NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL, -- 省份
	CITY VARCHAR(20),  --地级市
	DISTRICT VARCHAR(20), --市、县级市
	ADDRESS VARCHAR(60),
	HASSTOREHOUSE SMALLINT NOT NULL, --是否有库房 1：有 0：没有
	STOREHOUSEUNIQUEID INT,--库房ID
	IGNORECHECKER SMALLINT NOT NULL 	  --1-忽略质检（前台可以直接提交到审档队列），0-不忽略
);

--用户表
CREATE TABLE USERS (
	USERUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	HASHED VARCHAR(60) NOT NULL,
	ACTIVATED SMALLINT NOT NULL,
	COMPANYNAME VARCHAR(20),
	COMPANYUNIQUEID INT,
	COMMUNITYUNIQUEID INT,
	EMAIL VARCHAR(20),
	PHONE VARCHAR(20),
	FAX VARCHAR(20)
);

--用户配置文件
CREATE TABLE USERPROFILES (
	USERPROFILEUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	TITLE VARCHAR(20),
	PICTURE VARCHAR(40),
	MANAGERUNIQUEID INT,
	CREATEDBY VARCHAR(20),
	CREATORUNIQUEID INT NOT NULL,
	DATECREATED TIMESTAMP,
	DATELASTMODIFIED TIMESTAMP,
	LASTLOGON TIMESTAMP,
	SEX VARCHAR(4),
	EMAIL VARCHAR(20),
	LOCATION VARCHAR(120),
	PHONE VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20)
);

--业务类型
CREATE TABLE BUSINESS (
	BUSINESSUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	NEEDTOCHECK SMALLINT NOT NULL,--是否需要审档
	CHECKLEVEL VARCHAR(2) NOT NULL,  --审档级别
	CODE VARCHAR(4) NOT NULL --快捷编码
);

--数据字典
CREATE TABLE DATADICTIONARY (
	DICTIONARYUNIQUEID SERIAL PRIMARY KEY,
	ITEMTYPE SMALLINT NOT NULL,      --数据项类别 1-号牌种类 2-材料名称
	ITEMNAME VARCHAR(51) NOT NULL,   --数据项名称
	CODE VARCHAR(7) NOT NULL,         --快捷编码
	ORDERNUMBER NUMERIC(5,2) NOT NULL --顺序号 
);

--业务类型-数据字典
CREATE TABLE BUSINESSITEMS (
	ITEMUNIQUEID SERIAL PRIMARY KEY,
	BUSINESSCODE VARCHAR(4) NOT NULL,
	DICTIONARYCODE VARCHAR(7) NOT NULL
);

--机构-业务类型
CREATE TABLE COMPANYBUSINESSES (
	CBUNIQUEID SERIAL PRIMARY KEY,
	COMPANYUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--用户-业务类型
CREATE TABLE USERBUSINESSES (
	UBUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--上架号
CREATE TABLE FRAMENUMBER (
	FRAMEUNIQUEID SERIAL PRIMARY KEY,
	STOREHOUSENAME VARCHAR(20) NOT NULL, --库房名称
	FRAMECODE INT,--密集架号
	MAXCOLUMN INT NOT NULL,
	MAXROW INT NOT NULL,
	CELLCODE INT,--单元格号
	COL INT NOT NULL,
	ROW INT NOT NULL,
	VIN VARCHAR(50),--车辆识别代码
	CODE VARCHAR(20)--上架号，例如014-002-003-001(密集架号-列-行-文件夹序号）
);

--租户
CREATE TABLE TENANTS (
	TENANTUNIQUEID SERIAL PRIMARY KEY,
	TENANTNAME VARCHAR(20) NOT NULL
);
--社区-租户
CREATE TABLE COMMUNITYTENANTS (
	CTUNIQUEID SERIAL NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	TENANTUNIQUEID INT NOT NULL,
	FOREIGN KEY(COMMUNITYUNIQUEID) REFERENCES COMMUNITIES(COMMUNITYUNIQUEID),
	FOREIGN KEY(TENANTUNIQUEID) REFERENCES TENANTS(TENANTUNIQUEID),
	PRIMARY KEY(CTUNIQUEID, COMMUNITYUNIQUEID, TENANTUNIQUEID)
);
--站点
CREATE TABLE SITE (
	SITEUNIQUEID SERIAL PRIMARY KEY,
	SITENAME VARCHAR(20) NOT NULL,--站点名
	SITETYPE VARCHAR(20) NOT NULL,--站点类型
	HOSTADDR VARCHAR(50) NOT NULL,--主机地址
	PORT SMALLINT,--端口号
	DEFAULTREMOTEDIRECTORY VARCHAR(50), --默认目录
	USERNAME VARCHAR(20), --服务用户名
	PASSWORD VARCHAR(50), --密码
	MODE VARCHAR(10), --传输模式
	CHARSET VARCHAR(10), --字符集
	RUNNINGSTATUS SMALLINT NOT NULL, --运行状态 1运行 0停止
	CODE VARCHAR(7) NOT NULL --快捷编码
);

--站点容量
CREATE TABLE SITECAPACITY (
	SITECAPACITYUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	CAPACITY BIGINT,
	USEDSPACE BIGINT,
	UPDATETIMEMILLIS BIGINT,
	UNIT VARCHAR(4),
	UNITNUMBER VARCHAR(10),
	MAXBATCH INT, -- 最大批次数
	MAXBUSINESS INT -- 每批次内最大业务数
);

--站点内文件个数
CREATE TABLE SITEFOLDER (
	SITEFOLDERUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	BATCHCOUNT INT, --批次增长数
	BUSINESSCOUNT INT --业务数量
);

--社区-站点
CREATE TABLE COMMUNITYSITES (
	CSUNIQUEID SERIAL NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	FOREIGN KEY (COMMUNITYUNIQUEID)
		REFERENCES COMMUNITIES (COMMUNITYUNIQUEID),
	FOREIGN KEY (SITEUNIQUEID)
		REFERENCES SITE (SITEUNIQUEID),
	PRIMARY KEY (CSUNIQUEID, COMMUNITYUNIQUEID, SITEUNIQUEID)
);
--消息系统
CREATE TABLE MESSAGES (
	MESSAGEUNIQUEID SERIAL PRIMARY KEY,
	SUBJECT VARCHAR(50) NOT NULL,--标题
	MESSAGEBODY VARCHAR(200) NOT NULL,--消息体JSON
	CREATORUNIQUEID INT NOT NULL,--创建者ID
	DATECREATED TIMESTAMP, -- 创建时间
	SENTTIMES SMALLINT NOT NULL,--已发送次数
	REMINDERFREQUENCYID INT NOT NULL, -- 发送频率ID
	DELETED SMALLINT NOT NULL
);
--消息接收者
CREATE TABLE MESSAGERECIPIENT (
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收方ID
	RECIPIENTNAME VARCHAR(50) NOT NULL,--接收方名称
	RECIPIENTTYPE SMALLINT NOT NULL, --接收方类别
	MESSAGEUNIQUEID INT NOT NULL -- 消息ID
);
--提醒频率
CREATE TABLE REMINDERFREQUENCY (
	FREQUENCYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	FREQUENCY SMALLINT NOT NULL, -- 1-每天 7-每周
	ENABLED SMALLINT NOT NULL,--1-启用 0禁用
	STARTINGTIME TIMESTAMP,--起始时间
	ENDINGTIME TIMESTAMP -- 结束时间
);
--发送细节
CREATE TABLE SENDDETAILS(
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收者UserID
	MESSAGEUNIQUEID INT NOT NULL, --消息ID
	MARKEDASREAD SMALLINT NOT NULL, --0-未读 1已读
	VIEWNAME VARCHAR(20) --视图名称，如果等于空则接收方将在首个视图上显示消息
);

--质检队列
CREATE TABLE QUEUE_1 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	LOCKEDBYUSER INT,
	SENTBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID 如果companyUniqueId为空，表示本社区内任何审档都可以取，否则只允许本机审档构取。
	COMMUNITYUNIQUEID INT NOT NULL -- 社区ID 如果communityUniqueId，本社区内的质检只能取本社区队列。
);
--审档队列
CREATE TABLE QUEUE_2 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	LOCKEDBYUSER INT,
	SENTBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID 如果companyUniqueId为空，表示本社区内任何审档都可以取，否则只允许本机审档构取。
	COMMUNITYUNIQUEID INT NOT NULL -- 社区ID 如果communityUniqueId，本社区内的审档只能取本社区队列。
);
--确认审档队列
CREATE TABLE QUEUE_3 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	TRANSACTIONUNIQUEID INT NOT NULL,
	LOCKEDBYUSER INT,
	SENTBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID 如果companyUniqueId为空，表示本社区内任何审档都可以取，否则只允许本机审档构取。
	COMMUNITYUNIQUEID INT NOT NULL -- 社区ID 如果communityUniqueId，本社区内的审档/质检只能取本社区队列。
);
--角色表
CREATE TABLE ROLE (
	ROLEUNIQUEID SERIAL PRIMARY KEY,
	ROLENAME VARCHAR(20) NOT NULL,
	ROLETYPE VARCHAR(10) NOT NULL
);
--权限表
CREATE TABLE PERMISSION (
	PERMISSIONUNIQUEID SERIAL PRIMARY KEY,
	CATEGORYUNIQUEID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);
--权限类别表
CREATE TABLE PERMISSIONCATEGORY (
	CATEGORYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL
);
--用户与角色关系表
CREATE TABLE ROLEMEMBER (
	ROLEMEMBERUNIQUEID SERIAL NOT NULL,
	USERUNIQUEID INT NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	FOREIGN KEY (USERUNIQUEID)
		REFERENCES USERS (USERUNIQUEID),
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	PRIMARY KEY (ROLEMEMBERUNIQUEID, USERUNIQUEID, ROLEUNIQUEID)
);
--角色与权限关系表
CREATE TABLE ROLERIGHT (
	ROLERIGHTUNIQUEID SERIAL NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	PERMISSIONUNIQUEID INT NOT NULL,
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	FOREIGN KEY (PERMISSIONUNIQUEID)
		REFERENCES PERMISSION (PERMISSIONUNIQUEID),
	PRIMARY KEY (ROLERIGHTUNIQUEID, ROLEUNIQUEID, PERMISSIONUNIQUEID)
);

RETURN;
END
$BODY$
LANGUAGE plpgsql$$

--分表
DROP FUNCTION IF EXISTS splitup_large_table();
CREATE OR REPLACE FUNCTION splitup_large_table() RETURNS SETOF integer AS
$BODY$
BEGIN
    
    FOR i IN 0..255 LOOP
    RAISE NOTICE '%', i;

	-- 删除transaction表
	EXECUTE format('DROP TABLE IF EXISTS TRANSACTION%I','_'||i);
	-- 创建transaction表
	EXECUTE format('CREATE TABLE TRANSACTION%I(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,--业务主键ID
	BARCODE VARCHAR(50),--条形码
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	DATEFINISHED TIMESTAMP,--办结日期
	STATUS VARCHAR(20) NOT NULL,--状态名称
	SITECODE VARCHAR(4) NOT NULL,--站点编码
	BUSINESSCODE VARCHAR(4) NOT NULL, --业务类型编码
	COMMUNITYUNIQUEID INT NOT NULL, --社区ID
	COMPANYUNIQUEID INT NOT NULL,--机构ID
	LOCATIONCODE VARCHAR(20),--位置CDOE
	UUID VARCHAR(36) NOT NULL, --文件挂载ID
	CODE VARCHAR(15),--上架号
	CREATOR VARCHAR(20) NOT NULL, --录入人用户名
	INDEXNUMBER INT NOT NULL --业务顺序号
	)','_'||i);

	
	-- 删除document1表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_1%I','_'||i);
	-- 创建document1表
	EXECUTE format('CREATE TABLE DOCUMENTS_1%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,--文档主键ID
	UUID VARCHAR(36) NOT NULL,--文件挂载ID
	DICTIONARYCODE VARCHAR(7) NOT NULL,--材料CODE(数据字典CODE)
	FILEFULLPATH VARCHAR(120) NOT NULL,--真实文件相对路径
	THUMBNAIL BYTEA --缩略图
	)','_'||i);

	-- 删除document2表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_2%I','_'||i);
	-- 创建document2表
	EXECUTE format('CREATE TABLE DOCUMENTS_2%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,--文档主键ID
	UUID VARCHAR(36) NOT NULL,--文件挂载ID
	FILEFULLPATH VARCHAR(120) NOT NULL, --真实文件相对路径
	THUMBNAIL BYTEA --缩略图
	)','_'||i);

	-- 删除TRANSITION表
	EXECUTE format('DROP TABLE IF EXISTS TRANSITION%I','_'||i);
	-- 创建TRANSITION表
	EXECUTE format('CREATE TABLE TRANSITION%I(
	TRANSITIONUNIQUEID SERIAL PRIMARY KEY,--迁移主键ID
	TRANSACTIONUUID VARCHAR(36) NOT NULL,--业务记录UUID
	ACTION VARCHAR(20) NOT NULL,--事件动作
	DETAILS VARCHAR(120) NOT NULL,--描述json
	FROMUSERNAME VARCHAR(20) NOT NULL,--从用户
	TOUSERNAME VARCHAR(20) NOT NULL,--到用户
	DATEUPDATED TIMESTAMP NOT NULL --更新日期
	)','_'||i);
	
	-- 删除USEREVENT表
	EXECUTE format('DROP TABLE IF EXISTS USEREVENT%I','_'||i);
	-- 创建USEREVENT表
	EXECUTE format('CREATE TABLE USEREVENT%I(
	USEREVENTUNIQUEID SERIAL PRIMARY KEY,--事件主键ID
	USERNAME VARCHAR(20) NOT NULL,--用户名
	ACTION VARCHAR(20) NOT NULL,--事件动作
	DETAILS VARCHAR(120) NOT NULL,--描述json
	DATEUPDATED TIMESTAMP NOT NULL --更新日期
	)','_'||i);
	
    END LOOP;
    RETURN;
END
$BODY$
LANGUAGE plpgsql$$

SELECT * FROM create_tables()$$

SELECT * FROM splitup_large_table()$$
