DO
$do$
BEGIN 

	 
	
   FOR i IN 0..255 LOOP
	--RAISE NOTICE '%', i;
	

	-- 删除transaction表
	EXECUTE format('delete from TRANSACTION%I','_'||i);
	-- 创建transaction表
	/*
	EXECUTE format('CREATE TABLE TRANSACTION%I(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,
	BARCODE VARCHAR(50),
	PLATETYPE VARCHAR(20) NOT NULL,
	PLATENUMBER VARCHAR(20) NOT NULL,
	VIN VARCHAR(50) NOT NULL,
	DATECREATED TIMESTAMP NOT NULL,
	DATEMODIFIED TIMESTAMP,
	DATEFINISHED TIMESTAMP,
	STATUS VARCHAR(20) NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYUNIQUEID INT NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL,
	CITY VARCHAR(20) NOT NULL,
	PREFECTURE VARCHAR(20),
	DISTRICT VARCHAR(20),
	UUID VARCHAR(36) NOT NULL,
	CODE VARCHAR(15),--上架号
	TYPIST INT NOT NULL, --录入员
	INDEXNUMBER INT NOT NULL --业务顺序号
	)','_'||i);
	*/
	
	-- 删除document1表
	EXECUTE format('delete from DOCUMENTS_1%I','_'||i);
	-- 创建document1表
	/*EXECUTE format('CREATE TABLE DOCUMENTS_1%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY SMALLINT
	)','_'||i);
	*/

	-- 删除document2表
	EXECUTE format('delete from DOCUMENTS_2%I','_'||i);
	-- 创建document2表
	/*EXECUTE format('CREATE TABLE DOCUMENTS_2%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY SMALLINT
	)','_'||i);
	*/
	
	-- 删除document2表
	EXECUTE format('delete from TRANSITION%I','_'||i);
	
 
      
   END LOOP;
 
   
           delete from MESSAGES;
	 delete from  MESSAGERECIPIENT;
	 delete from  REMINDERFREQUENCY;
	 delete from SENDDETAILS;
   delete from QUEUE_3;
	delete from QUEUE_2;
	delete from QUEUE_1;
END
$do$;