DO
$do$
BEGIN 

	DROP FUNCTION IF EXISTS INSERT_DATA();
	DROP FUNCTION IF EXISTS CREATE_TABLES();
	DROP FUNCTION IF EXISTS SPLITUP_LARGE_TABLE();
	DROP FUNCTION IF EXISTS CREATE_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR);
	DROP FUNCTION IF EXISTS CREATE_PAGINGCOUNT2(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
	DROP FUNCTION IF EXISTS CREATE_SEARCH(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
	
   FOR i IN 0..255 LOOP
	--RAISE NOTICE '%', i;
	

	-- 删除transaction表
	EXECUTE format('DROP TABLE IF EXISTS TRANSACTION%I','_'||i);
	-- 创建transaction表
	/*
	EXECUTE format('CREATE TABLE TRANSACTION%I(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,
	BARCODE VARCHAR(50),
	PLATETYPE VARCHAR(20) NOT NULL,
	PLATENUMBER VARCHAR(20) NOT NULL,
	VIN VARCHAR(50) NOT NULL,
	DATECREATED TIMESTAMP NOT NULL,
	DATEMODIFIED TIMESTAMP,
	DATEFINISHED TIMESTAMP,
	STATUS VARCHAR(20) NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYUNIQUEID INT NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL,
	CITY VARCHAR(20) NOT NULL,
	PREFECTURE VARCHAR(20),
	DISTRICT VARCHAR(20),
	UUID VARCHAR(36) NOT NULL,
	CODE VARCHAR(15),--上架号
	TYPIST INT NOT NULL, --录入员
	INDEXNUMBER INT NOT NULL --业务顺序号
	)','_'||i);
	*/
	
	-- 删除document1表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_1%I','_'||i);
	-- 创建document1表
	/*EXECUTE format('CREATE TABLE DOCUMENTS_1%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY SMALLINT
	)','_'||i);
	*/

	-- 删除document2表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_2%I','_'||i);
	-- 创建document2表
	/*EXECUTE format('CREATE TABLE DOCUMENTS_2%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL,
	ALIAS VARCHAR(60) NOT NULL,
	FILENAME VARCHAR(60) NOT NULL,
	FILEFULLPATH VARCHAR(120) NOT NULL,
	CATEGORY SMALLINT
	)','_'||i);
	*/
	
	-- 删除document2表
	EXECUTE format('DROP TABLE IF EXISTS TRANSITION%I','_'||i);
	
	EXECUTE format('DROP TABLE IF EXISTS USEREVENT%I','_'||i);
      
   END LOOP;
   
        DROP TABLE IF EXISTS RETURN_TABLE;
        DROP TABLE IF EXISTS MESSAGES;
	DROP TABLE IF EXISTS MESSAGERECIPIENT;
	DROP TABLE IF EXISTS REMINDERFREQUENCY;
	DROP TABLE IF EXISTS SENDDETAILS;
	DROP TABLE IF EXISTS COMMUNITYSITES;
	DROP TABLE IF EXISTS COMMUNITYTENANTS;
	DROP TABLE IF EXISTS TENANTS;
	DROP TABLE IF EXISTS COMPANYBUSINESSES;
	DROP TABLE IF EXISTS USERBUSINESSES;
	DROP TABLE IF EXISTS BUSINESSITEMS;
	DROP TABLE IF EXISTS DATADICTIONARY;
	DROP TABLE IF EXISTS AUDITS;
	DROP TABLE IF EXISTS QUEUE_3;
	DROP TABLE IF EXISTS QUEUE_2;
	DROP TABLE IF EXISTS QUEUE_1;
	DROP TABLE IF EXISTS SITEFOLDER;
	DROP TABLE IF EXISTS SITECAPACITY;
	DROP TABLE IF EXISTS SITE;
	DROP TABLE IF EXISTS BUSINESS; 
	DROP TABLE IF EXISTS ROLERIGHT;
	DROP TABLE IF EXISTS ROLEMEMBER;
	DROP TABLE IF EXISTS PERMISSIONCATEGORY;
	DROP TABLE IF EXISTS PERMISSION;
	DROP TABLE IF EXISTS ROLE;
	DROP TABLE IF EXISTS USERPROFILES;
	DROP TABLE IF EXISTS USERS;
	DROP TABLE IF EXISTS PORTFOLIO;
	DROP TABLE IF EXISTS FILEBOX;
	DROP TABLE IF EXISTS DENSEFRAME;
	DROP TABLE IF EXISTS STOREHOUSE;
	DROP TABLE IF EXISTS COMPANIES;
	DROP TABLE IF EXISTS COMMUNITIES;
	DROP TABLE IF EXISTS FRAMENUMBER;
	DROP TABLE IF EXISTS IMAGING;
	DROP TABLE IF EXISTS SYSTEM_SETTINGS;
	DROP TABLE IF EXISTS COMMONPROBLEMS;
   
END
$do$;