DROP FUNCTION IF EXISTS INSERT_DATA();
DROP FUNCTION IF EXISTS CREATE_SEARCH(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
DROP TABLE IF EXISTS RETURN_TABLE;
CREATE TABLE RETURN_TABLE(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,--业务主键ID
	BARCODE VARCHAR(50),--条形码
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	DATEFINISHED TIMESTAMP,--办结日期
	STATUS VARCHAR(20) NOT NULL,--状态名称
	SITECODE VARCHAR(4) NOT NULL,--站点编码
	BUSINESSCODE VARCHAR(4) NOT NULL, --业务类型编码
	COMMUNITYUNIQUEID INT NOT NULL, --社区ID
	COMPANYUNIQUEID INT NOT NULL,--机构ID
	LOCATIONCODE VARCHAR(30),--位置CDOE
	BATCH INT NOT NULL,--批次号,默认最大1000个批次，每批次最多放3000文件夹。
	UUID VARCHAR(36) NOT NULL, --文件挂载ID
	CODE VARCHAR(15),--上架号
	CREATOR VARCHAR(20) NOT NULL, --录入人用户名
	INDEXNUMBER INT NOT NULL --业务顺序号
 );

DROP FUNCTION IF EXISTS CREATE_TABLES();
CREATE OR REPLACE FUNCTION CREATE_TABLES() RETURNS SETOF integer AS
$BODY$
BEGIN

DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS MESSAGERECIPIENT;
DROP TABLE IF EXISTS REMINDERFREQUENCY;
DROP TABLE IF EXISTS SENDDETAILS;
DROP TABLE IF EXISTS COMMUNITYSITES;
DROP TABLE IF EXISTS COMMUNITYTENANTS;
DROP TABLE IF EXISTS TENANTS;
DROP TABLE IF EXISTS COMPANYBUSINESSES;
DROP TABLE IF EXISTS USERBUSINESSES;
DROP TABLE IF EXISTS BUSINESSITEMS;
DROP TABLE IF EXISTS DATADICTIONARY;
DROP TABLE IF EXISTS QUEUE_3;
DROP TABLE IF EXISTS QUEUE_2;
DROP TABLE IF EXISTS QUEUE_1;
--DROP TABLE IF EXISTS SITEFOLDER;
--DROP TABLE IF EXISTS SITECAPACITY;
--DROP TABLE IF EXISTS SITE;
DROP TABLE IF EXISTS BUSINESS; 
DROP TABLE IF EXISTS ROLERIGHT;
DROP TABLE IF EXISTS ROLEMEMBER;
DROP TABLE IF EXISTS PERMISSIONCATEGORY;
DROP TABLE IF EXISTS PERMISSION;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USERPROFILES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FRAMENUMBER;
DROP TABLE IF EXISTS COMPANIES;
DROP TABLE IF EXISTS COMMUNITIES;
DROP TABLE IF EXISTS IMAGING;
DROP TABLE IF EXISTS IMAGING;
DROP TABLE IF EXISTS SYSTEM_SETTINGS;
DROP TABLE IF EXISTS COMMONPROBLEMS;

--系统设置表
CREATE TABLE SYSTEM_SETTINGS(
	SETTINGUNIQUEID SERIAL PRIMARY KEY,
	K VARCHAR(20) NOT NULL,--键
	V VARCHAR(20) NOT NULL--值
);

--影像化
CREATE TABLE IMAGING(
	IMAGINGUNIQUEID SERIAL PRIMARY KEY,
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	STATUS VARCHAR(20) NOT NULL,--记录状态
	CREATOR VARCHAR(20) NOT NULL --录入人用户名
);

--社区
CREATE TABLE COMMUNITIES (
	COMMUNITYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYNAME VARCHAR(20) NOT NULL,
	COMMUNITYDESCRIPTION VARCHAR(60),
	GROUPID INT NOT NULL,
	LEVEL SMALLINT NOT NULL
);

--机构
CREATE TABLE COMPANIES (
	COMPANYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYNAME VARCHAR(20) NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL, -- 省份
	CITY VARCHAR(20),  --地级市
	DISTRICT VARCHAR(20), --市、县级市
	ADDRESS VARCHAR(60),
	HASSTOREHOUSE SMALLINT NOT NULL, --是否有库房 1：有 0：没有
	STOREHOUSENAME VARCHAR(20),--库房名称
	IGNORECHECKER SMALLINT NOT NULL, 	  --1-忽略质检（前台可以直接提交到审档队列），0-不忽略
	CATEGORY VARCHAR(20) --车管所/二手车/4S店
);

--用户表
CREATE TABLE USERS (
	USERUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	HASHED VARCHAR(60) NOT NULL,
	ACTIVATED SMALLINT NOT NULL,
	COMPANYNAME VARCHAR(20),
	COMPANYUNIQUEID INT,
	COMMUNITYUNIQUEID INT,
	EMAIL VARCHAR(20),
	PHONE VARCHAR(20),
	FAX VARCHAR(20)
);

--用户配置文件
CREATE TABLE USERPROFILES (
	USERPROFILEUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	TITLE VARCHAR(20),
	PICTURE VARCHAR(40),
	MANAGERUNIQUEID INT,
	CREATEDBY VARCHAR(20),
	CREATORUNIQUEID INT NOT NULL,
	DATECREATED TIMESTAMP,
	DATELASTMODIFIED TIMESTAMP,
	LASTLOGON TIMESTAMP,
	SEX VARCHAR(4),
	EMAIL VARCHAR(20),
	LOCATION VARCHAR(120),
	PHONE VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20)
);

--业务类型
CREATE TABLE BUSINESS (
	BUSINESSUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	CHECKLEVEL VARCHAR(4) NOT NULL,  --审档级别
	CODE VARCHAR(4) NOT NULL --快捷编码
);

--数据字典
CREATE TABLE DATADICTIONARY (
	DICTIONARYUNIQUEID SERIAL PRIMARY KEY,
	ITEMTYPE SMALLINT NOT NULL,      --数据项类别 1-号牌种类 2-材料名称
	ITEMNAME VARCHAR(51) NOT NULL,   --数据项名称
	CODE VARCHAR(7) NOT NULL       --快捷编码
);

--业务类型-数据字典
CREATE TABLE BUSINESSITEMS (
	ITEMUNIQUEID SERIAL PRIMARY KEY,
	BUSINESSCODE VARCHAR(4) NOT NULL,
	DICTIONARYCODE VARCHAR(7) NOT NULL
);

--机构-业务类型
CREATE TABLE COMPANYBUSINESSES (
	CBUNIQUEID SERIAL PRIMARY KEY,
	COMPANYUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--用户-业务类型
CREATE TABLE USERBUSINESSES (
	UBUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--上架号
CREATE TABLE FRAMENUMBER (
	FRAMEUNIQUEID SERIAL PRIMARY KEY,
	STOREHOUSENAME VARCHAR(20) NOT NULL, --库房名称
	FRAMECODE INT,--密集架号
	MAXCOLUMN INT NOT NULL,
	MAXROW INT NOT NULL,
	CELLCODE INT,--单元格号
	COL INT NOT NULL,
	ROW INT NOT NULL,
	VIN VARCHAR(50),--车辆识别代码
	CODE VARCHAR(20)--上架号，例如014-002-003-001(密集架号-列-行-文件夹序号）
);

----租户
--CREATE TABLE TENANTS (
--	TENANTUNIQUEID SERIAL PRIMARY KEY,
--	TENANTNAME VARCHAR(20) NOT NULL
--);
----社区-租户
--CREATE TABLE COMMUNITYTENANTS (
--	CTUNIQUEID SERIAL NOT NULL,
--	COMMUNITYUNIQUEID INT NOT NULL,
--	TENANTUNIQUEID INT NOT NULL,
--	FOREIGN KEY(COMMUNITYUNIQUEID) REFERENCES COMMUNITIES(COMMUNITYUNIQUEID),
--	FOREIGN KEY(TENANTUNIQUEID) REFERENCES TENANTS(TENANTUNIQUEID),
--	PRIMARY KEY(CTUNIQUEID, COMMUNITYUNIQUEID, TENANTUNIQUEID)
--);

/*
--站点
CREATE TABLE SITE (
	SITEUNIQUEID SERIAL PRIMARY KEY,
	SITENAME VARCHAR(20) NOT NULL,--站点名
	SITETYPE VARCHAR(20) NOT NULL,--站点类型
	HOSTADDR VARCHAR(50) NOT NULL,--主机地址
	PORT SMALLINT,--端口号
	DEFAULTREMOTEDIRECTORY VARCHAR(50), --默认目录
	USERNAME VARCHAR(20), --服务用户名
	PASSWORD VARCHAR(50), --密码
	MODE VARCHAR(10), --传输模式
	CHARSET VARCHAR(10), --字符集
	RUNNINGSTATUS SMALLINT NOT NULL, --运行状态 1运行 0停止
	CODE VARCHAR(7) NOT NULL --快捷编码
);

--站点容量
CREATE TABLE SITECAPACITY (
	SITECAPACITYUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	CAPACITY BIGINT,
	USEDSPACE BIGINT,
	UPDATETIMEMILLIS BIGINT,
	UNIT VARCHAR(4),
	UNITNUMBER VARCHAR(10),
	MAXBATCH INT, -- 最大批次数
	MAXBUSINESS INT -- 每批次内最大业务数
);

--站点内文件个数
CREATE TABLE SITEFOLDER (
	SITEFOLDERUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	BATCHCOUNT INT, --批次增长数
	BUSINESSCOUNT INT --业务数量
	
);
*/
--社区-站点
CREATE TABLE COMMUNITYSITES (
	CSUNIQUEID SERIAL NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	FOREIGN KEY (COMMUNITYUNIQUEID)
		REFERENCES COMMUNITIES (COMMUNITYUNIQUEID),
	FOREIGN KEY (SITEUNIQUEID)
		REFERENCES SITE (SITEUNIQUEID),
	PRIMARY KEY (CSUNIQUEID, COMMUNITYUNIQUEID, SITEUNIQUEID)
);
--消息系统
CREATE TABLE MESSAGES (
	MESSAGEUNIQUEID SERIAL PRIMARY KEY,
	SUBJECT VARCHAR(50) NOT NULL,--标题
	CONTENT VARCHAR(200) NOT NULL,--内容
	MATEDATA VARCHAR(200) NOT NULL,--元数据
	CREATORUNIQUEID INT NOT NULL,--创建者ID
	DATECREATED TIMESTAMP, -- 创建时间
	SENTTIMES SMALLINT NOT NULL,--已发送次数
	REMINDERFREQUENCYID INT NOT NULL, -- 发送频率ID
	DELETED SMALLINT NOT NULL
);
--消息接收者
CREATE TABLE MESSAGERECIPIENT (
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收方ID
	RECIPIENTNAME VARCHAR(50) NOT NULL,--接收方名称
	RECIPIENTTYPE SMALLINT NOT NULL, --接收方类别
	MESSAGEUNIQUEID INT NOT NULL -- 消息ID
);
--提醒频率
CREATE TABLE REMINDERFREQUENCY (
	FREQUENCYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	FREQUENCY SMALLINT NOT NULL, -- 1-每天 7-每周
	ENABLED SMALLINT NOT NULL,--1-启用 0禁用
	STARTINGTIME TIMESTAMP,--起始时间
	ENDINGTIME TIMESTAMP -- 结束时间
);
--发送细节
CREATE TABLE SENDDETAILS(
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收者UserID
	MESSAGEUNIQUEID INT NOT NULL, --消息ID
	MARKEDASREAD SMALLINT NOT NULL, --0-未读 1已读
	VIEWNAME VARCHAR(20) --视图名称，如果等于空则接收方将在首个视图上显示消息
);

--质检队列
CREATE TABLE QUEUE_1 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。质检只能取本社区和本机构的记录
);
--审档队列
CREATE TABLE QUEUE_2 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。普通审档只能取本社区和本机构的记录
);
--确认审档队列
CREATE TABLE QUEUE_3 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。确认审档只能取本社区和本机构的记录
);
--角色表
CREATE TABLE ROLE (
	ROLEUNIQUEID SERIAL PRIMARY KEY,
	ROLENAME VARCHAR(20) NOT NULL,
	ROLETYPE VARCHAR(10) NOT NULL
);
--权限表
CREATE TABLE PERMISSION (
	PERMISSIONUNIQUEID SERIAL PRIMARY KEY,
	CATEGORYUNIQUEID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);
--权限类别表
CREATE TABLE PERMISSIONCATEGORY (
	CATEGORYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL
);
--用户与角色关系表
CREATE TABLE ROLEMEMBER (
	ROLEMEMBERUNIQUEID SERIAL NOT NULL,
	USERUNIQUEID INT NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	FOREIGN KEY (USERUNIQUEID)
		REFERENCES USERS (USERUNIQUEID),
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	PRIMARY KEY (ROLEMEMBERUNIQUEID, USERUNIQUEID, ROLEUNIQUEID)
);
--角色与权限关系表
CREATE TABLE ROLERIGHT (
	ROLERIGHTUNIQUEID SERIAL NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	PERMISSIONUNIQUEID INT NOT NULL,
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	FOREIGN KEY (PERMISSIONUNIQUEID)
		REFERENCES PERMISSION (PERMISSIONUNIQUEID),
	PRIMARY KEY (ROLERIGHTUNIQUEID, ROLEUNIQUEID, PERMISSIONUNIQUEID)
);
--常见问题
CREATE TABLE COMMONPROBLEMS (
	PROBLEMUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	PROBLEM VARCHAR(60) NOT NULL,
	FREQUENCY BIGINT NOT NULL
);

RETURN;
END
$BODY$
LANGUAGE PLPGSQL;
 

--获取分页数
DROP FUNCTION IF EXISTS CREATE_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR);
CREATE OR REPLACE FUNCTION CREATE_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR) RETURNS SETOF INTEGER AS
$BODY$
DECLARE
  A INTEGER := 0;
  B INTEGER := 0;
  L INTEGER := 0;
BEGIN
	L := CHAR_LENGTH(KEYWORD);
	IF L = 0 THEN
		SELECT COUNT(IMAGINGUNIQUEID) INTO A FROM IMAGING;
	ELSE
		SELECT COUNT(IMAGINGUNIQUEID) INTO A FROM IMAGING WHERE PLATENUMBER ILIKE '%'||KEYWORD||'%';
	END IF;
   
    B := (A%LIMIT2); --RAISE NOTICE  '%', B;
   IF A <= LIMIT2 THEN
     RETURN NEXT 1;
   ELSIF B > 0 THEN 
     RETURN NEXT A/LIMIT2+1;
   ELSE
     RETURN NEXT A/LIMIT2;
   END IF;
   RETURN;
END
$BODY$
LANGUAGE PLPGSQL;

--分页页数
DROP FUNCTION IF EXISTS CREATE_PAGINGCOUNT2(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
CREATE OR REPLACE FUNCTION CREATE_PAGINGCOUNT2(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR) RETURNS BIGINT AS
$BODY$
DECLARE
  B INTEGER := 0;
  L INTEGER := 0;
  RS BIGINT := 0;
  TOTAL BIGINT := 0;
  EX_SQL VARCHAR;
BEGIN
   EX_SQL :='';
   L := CHAR_LENGTH(KEYWORD);
   --RAISE NOTICE '%', L;

   IF L = 9 OR L =10 THEN
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE PLATENUMBER ILIKE '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   ELSIF L = 15 THEN
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE BARCODE ILIKE '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   ELSIF L = 19 THEN
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE VIN ILIKE '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;
   ELSE
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE VIN ILIKE '''||KEYWORD||''' OR BARCODE ILIKE '''||KEYWORD||''' OR PLATENUMBER ILIKE '''||KEYWORD||''' ';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   END IF;
    --RAISE NOTICE '%', TOTAL;

    B := (TOTAL%LIMIT2);
    IF TOTAL <= LIMIT2 THEN
     RETURN 1;
   ELSIF B > 0 THEN 
     RETURN TOTAL/LIMIT2+1;
   ELSE
     RETURN TOTAL/LIMIT2;
   END IF;
 
END
$BODY$
LANGUAGE PLPGSQL;

--获取模糊查询
CREATE OR REPLACE FUNCTION CREATE_SEARCH(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR) RETURNS SETOF RETURN_TABLE AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';
   IF LIMIT2 = -1 THEN
      LIMIT_STR := '';
   ELSE
      LIMIT_STR := ' LIMIT '''||LIMIT2||''' OFFSET '''||OFFSET2||'''';
   END IF;
   
   L := CHAR_LENGTH(KEYWORD);
   IF L = 9 OR L =10 THEN
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE PLATENUMBER ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_255 WHERE PLATENUMBER ILIKE '''||KEYWORD||'''' || LIMIT_STR;
   ELSIF L = 15 THEN
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE BARCODE ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_255 WHERE BARCODE ILIKE '''||KEYWORD||'''' || LIMIT_STR;
   ELSIF L = 19 THEN
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE VIN ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_255 WHERE VIN ILIKE '''||KEYWORD||'''' || LIMIT_STR;
   ELSE
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE BARCODE ILIKE '''||KEYWORD||''' OR PLATENUMBER ILIKE '''||KEYWORD||''' OR VIN ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT * FROM "'||COMMUNITYNAME||'".TRANSACTION_255 WHERE BARCODE ILIKE '''||KEYWORD||''' OR PLATENUMBER ILIKE '''||KEYWORD||''' OR VIN ILIKE '''||KEYWORD||'''' || LIMIT_STR;

   END IF;
   
   --RAISE NOTICE '%', EX_SQL;
   RETURN QUERY EXECUTE EX_SQL;
END
$BODY$
LANGUAGE PLPGSQL;

DROP FUNCTION IF EXISTS INSERT_DATA();
CREATE OR REPLACE FUNCTION INSERT_DATA() RETURNS SETOF integer AS
$BODY$
BEGIN
	
	----插入社区
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('LN', '辽宁省社区', 1, 1);
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('DL', '大连市社区', 1, 2);
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('ZH', '庄河市社区', 1, 3);

	----插入机构
    INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (2,'大连市车管所','210000','210200','210202','泉水',1,NULL,0,'车管所');
 	INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (2,'大连市二手车市场','210000','210200','210211','泉水',0,NULL,1,'二手车');
   	INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (3,'庄河市车管所','210000','210200','210283','',1,NULL,0,'车管所');

	
    --插入系统用户
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('system','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'',0,0,'sys1@max.com','047-5831-01',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (1,'系统管理员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','车','管');
	
	
	 --a
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('a','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'a@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (2,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','a','');
	
	--b
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('b','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'b@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (3,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','b','');
	
	--c
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('c','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'c@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (4,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','c','');
	
	--d
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('d','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'d@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (5,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','d','');
	
 	--e
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('e','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'e@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (6,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','e','');
	
	--f
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('f','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'f@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (7,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','f','');
	
	
	--g
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('g','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'g@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (8,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','g','');
	
	--h
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('h','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'h@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (9,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','h','');
	
	--i
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('i','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'i@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (10,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','i','');
	
	--j
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('j','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'j@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (11,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','j','');
	
	
	--k
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('k','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'k@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (12,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','k','');
	
	--l
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('l','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'庄河市车管所',3,3,'l@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (13,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','l','');
	
	
	--m
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('m','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'庄河市车管所',3,3,'m@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (14,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','m','');
	
	--n
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('n','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'庄河市车管所',3,3,'n@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (15,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','n','');
	
	--插入系统权限类别
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('登录类别');--A 1
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('个人配置');--B 2
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理用户');--C 3
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理角色');--D 4
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理权限');--E 5
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理机构');--F 6
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理社区');--G 7
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('高拍仪');  --H 8
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理查询');--J 9
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理站点');--K 10
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('广播消息');--L 11
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('数据字典');--M 12
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('业务类型');--N 13
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理范围');--O 14
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理库房');--P 15
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理服务器');--Q 16
	
	--插入所有权限
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A1','管理员','管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A2','前台','前台用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A3','质检','质检用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A4','审档','审档用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A5','查询','数据查询用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A6','上架下架','上架下架用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A7','确认审档','只对一级审档业务确认审档');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A8','影像化管理员','影像化管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A9','影像化录入','影像化录入');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A10','影像化质检','影像化质检');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B1','更改个人资料','更改个人资料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B2','更改密码','更改密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C1','创建','创建用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C2','编辑','编辑用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C3','删除','删除用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C4','查看','查看用户列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C5','分配角色','为用户分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C6','分配业务','为用户分配业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C7','重置密码','为用户重置密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D1','创建','创建角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D2','编辑','编辑角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D3','删除','删除角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D4','分配用户','为角色分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D5','设置权限','为角色分配权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D6','查看','查看角色列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E1','分配角色','为权限分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E2','编辑','编辑权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E3','查看','查看权限列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F1','创建','创建机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F2','编辑','编辑机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F3','删除','删除机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F4','分配用户','为机构分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F5','管理库房','管理库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F6','查看','查看机构列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F7','设置','设置业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G1','创建','创建社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G2','编辑','编辑社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G3','删除','删除社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G4','分配机构','分配机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G5','查看','查看社区列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G6','分配站点','为社区分配站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'H1','更改高拍仪','更改高拍仪');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'J1','删除','删除业务记录及其所有原文');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K1','创建','创建站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K2','编辑','编辑站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K3','删除','删除站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K4','查看','查看站点列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K5','分配社区','为站点分配社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K6','操作','对站点进行启动/停止/测试连接操作');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L1','发送消息','发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L2','查看','查看消息列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L3','设置','设置定时发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L4','删除','删除消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M1','创建','创建数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M2','编辑','编辑数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M3','删除','删除数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M4','查看','查看数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N1','创建','创建业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N2','编辑','编辑业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N3','删除','删除业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N4','查看','查看业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N5','设置','设置业务材料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'O1','社区范围内','社区管理员既可以管社区也可以管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'O2','机构范围内','机构管理员只允许管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P1','创建','创建库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P2','编辑','编辑库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P3','删除','删除库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P4','查看','查看库房列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P5','分配机构','为库房分配一个机构（通常机构是车管所）');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P6','管理密集架','管理密集架');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(16,'Q1','查看','查看服务器列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(16,'Q2','编辑','编辑服务器配置信息');
	
	--插入全部角色
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('系统管理员', '系统内置');	--1
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('前台', '自定义');	--2
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('质检', '自定义');	--3
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('审档', '自定义');	--4
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('查询', '自定义');	--5
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('上架下架', '自定义');	--6
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('确认审档', '自定义');	--7
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化管理员', '自定义');	--8
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化录入', '自定义');	--9
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化质检', '自定义');	--10
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连社区管理员', '自定义');	--11
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连车管所管理员', '自定义');	--12
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('庄河社区管理员', '自定义');	--13
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('庄河车管所管理员', '自定义');	--14
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连二手车管理员', '自定义');	--15

	
	--插入系统管理员权限
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,11);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,12);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,13);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,14);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,15);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,16);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,17);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,18);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,19);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,20);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,21);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,22);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,23);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,24);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,25);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,26);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,27);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,28);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,29);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,30);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,31);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,32);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,33);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,34);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,35);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,36);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,37);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,38);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,39);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,40);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,41);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,42);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,43);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,44);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,45);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,46);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,47);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,48);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,49);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,50);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,51);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,52);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,53);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,54);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,55);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,56);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,57);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,58);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,59);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,60);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,61);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,62);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,65);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,66);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,67);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,68);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,69);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,70);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,71);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,72);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,73);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,74);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,75);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,76);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(2,2);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(3,3);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(4,4);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(5,5);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(6,6);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(7,7);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(8,8);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(9,9);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(10,10);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(11,1);
    INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(11,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(12,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(12,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(13,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(13,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(14,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(14,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(15,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(15,64);
	
	--插入system用户角色关系
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(1,1); --为system用设置角色
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(2,2);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(3,3);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(4,4);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(5,5);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(6,6);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(7,7);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(8,8);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(9,9);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(10,10);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(11,11);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(12,12);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(13,13);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(14,2);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(15,3);
	
	
	--插入业务类型
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('注册登记','','0001');--1
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转移登记','','0003');--2
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('抵押登记','一级审档','0004');--3
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解除抵押登记','二级审档','0005');--4
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('质押备案','二级审档','0006');--5
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解除质押备案','二级审档','0007');--6
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补领登记证书','二级审档','0008');--7
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('换领登记证书','二级审档','0009');--8
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('申领登记证书','二级审档','0010');--9
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('登记事项更正','二级审档','0011');--10
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补建机动车档案','二级审档','0012');--11
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转入机动车','二级审档','0013');--12
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('影像化档案信息更正','二级审档','0014');--13
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更机动车所有人姓名/名称','二级审档','0021');--14
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更共同所有人姓名/名称','二级审档','0022');--15
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更使用性质','二级审档','0023');--16
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换发动机','二级审档','0024');--17
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换车身/车架','二级审档','0025');--18
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更车身颜色','二级审档','0026');--19
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换整车','二级审档','0027');--19
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('住所迁出车管所管辖区域','二级审档','0028');--20
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('重新打刻发动机号码','二级审档','0029');--21
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转出/注销恢复','二级审档','0031');--22
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('重新打刻车辆识别','二级审档','0210');--23
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更身份证明名称/号码','二级审档','0211');--24
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('加装残疾人操纵辅助装备','二级审档','0214');--25
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('拆除残疾人操纵辅助装置','二级审档','0215');--26
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记','二级审档','0216');--27
	
	----数据字典
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'1-大型汽车','A001');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'2-小型汽车','A002');--type1:号牌种类
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'辽宁省','210000');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'大连市','210200');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'中山区','210202');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'西岗区','210203');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'沙河口区','210204');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'甘井子区','210211');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'旅顺口区','210212');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'金州区','210213');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'长海县','210224');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'瓦房店市','210281');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'普兰店区','210282');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'庄河市','210283');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注册、转移、注销登记转入申请表》原件','A001'); --type3:代表业务材料自己弄
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有人身份证明复印件','A002');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车查验记录表原件','A003');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆照片','A040');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'拓印膜','A041');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆购置税完税证明副联原件','A004');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车的来历证明原件或复印件','A005');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'合格证','A006');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进口车5部位照片','A007');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车变更登记备案申请表','A008');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更证明','A009');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更前机动车所有人身份证明','A010');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'共同所有的公证证明或证明夫妻关系的居民户口簿和结婚证','A011');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更使用性质证明','A012');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车安全技术检验合格证明','A013');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术鉴定证明或公安机关发还证明','A014');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现合格证','A015');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原合格证','A016');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行驶证原件','A017');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'操纵辅助装置加装合格证明','A018');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'安全技术检验合格证明','A019');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现机动车所有人身份证明','A020');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车所有人身份证明','A021');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有权转移证明','A022');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车抵押登记或者质押备案申请表','A023');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押权人身份证明','A024');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押合同','A025');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》','A026');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明','A027');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民检察院、行政执法部门未得到登记证书证明','A029');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车勘误登记申请表','A030');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'书面报告','A031');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准补建机动车档案文件','A032');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'该机动车在系统中的所有记录信息','A033');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'核对公函','A034');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料','A035');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'影像化档案信息更正申请表','A036');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'申请表','A037');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'转出注销相关资料','A038');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其他资料','A039');
	
	----插入业务材料关系
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A001');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'A004');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0003', 'A005');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0003', 'A006');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0004', 'A007');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0004', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0005', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0005', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A009');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0021', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A010');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A011');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0022', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A012');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0023', 'A039');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A008');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A002');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A003');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A012');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A017');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0024', 'A039');
	
	 	
    ----插入系统设置
    INSERT INTO SYSTEM_SETTINGS(K, V) VALUES ('高拍仪', '无锡华通H6-1'); --默认使用无锡华通H6-1
    ----默认站点
 --   INSERT INTO SITE(SITENAME,SITETYPE,HOSTADDR,PORT,DEFAULTREMOTEDIRECTORY,USERNAME,PASSWORD,MODE,CHARSET,RUNNINGSTATUS,CODE) VALUES('文件站点1','File','C:\Demo\pictures',0,'/','','','主动','UTF-8',1,'DL01');
 --   INSERT INTO SITECAPACITY(SITEUNIQUEID, CAPACITY, USEDSPACE, UPDATETIMEMILLIS, UNIT, UNITNUMBER, MAXBATCH, MAXBUSINESS) VALUES (1, 2199023255552, 0, 1538146213038, 'TB', 2, 1000,3000);
 --   INSERT INTO SITEFOLDER(SITEUNIQUEID, BATCHCOUNT, BUSINESSCOUNT) VALUES (1, 1, 0);

    ----站点和社区关系
    INSERT INTO COMMUNITYSITES(COMMUNITYUNIQUEID, SITEUNIQUEID) VALUES (2, 1);
    INSERT INTO COMMUNITYSITES(COMMUNITYUNIQUEID, SITEUNIQUEID) VALUES (3, 1);
 	
  RETURN;
END
$BODY$
LANGUAGE plpgsql;
 
SELECT * FROM CREATE_TABLES();

SELECT * FROM INSERT_DATA();

SELECT * FROM CREATE_PAGINGCOUNT(3,'');

SELECT * FROM CREATE_PAGINGCOUNT2(20, '%'||'11'||'%','DL');

SELECT * FROM CREATE_SEARCH(20,0,'%'||'1'||'%','DL');


