DO
$do$
BEGIN 

   FOR i IN 0..255 LOOP
	--RAISE NOTICE '%', i;
	-- 删除transaction表
	EXECUTE format('DROP TABLE IF EXISTS TRANSACTION%I','_'||i);
	-- 创建transaction表
	EXECUTE format('CREATE TABLE TRANSACTION%I(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,--业务主键ID
	BARCODE VARCHAR(50),--条形码
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	DATEFINISHED TIMESTAMP,--办结日期
	STATUS VARCHAR(20) NOT NULL,--状态名称
	SITECODE VARCHAR(4) NOT NULL,--站点编码
	BUSINESSCODE VARCHAR(4) NOT NULL, --业务类型编码
	COMMUNITYUNIQUEID INT NOT NULL, --社区ID
	COMPANYUNIQUEID INT NOT NULL,--机构ID
	LOCATIONCODE VARCHAR(30),--位置CDOE
	BATCH INT NOT NULL,--批次号,默认最大1000个批次，每批次最多放3000文件夹。
	UUID VARCHAR(36) NOT NULL, --文件挂载ID
	CODE VARCHAR(15),--上架号
	CREATOR VARCHAR(20) NOT NULL, --录入人用户名
	INDEXNUMBER INT NOT NULL --业务顺序号
	)','_'||i);

	
	-- 删除document1表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_1%I','_'||i);
	-- 创建document1表
	EXECUTE format('CREATE TABLE DOCUMENTS_1%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,--文档主键ID
	UUID VARCHAR(36) NOT NULL,--文件挂载ID
	DICTIONARYCODE VARCHAR(7) NOT NULL,--材料CODE(数据字典CODE)
	FILEFULLPATH VARCHAR(120) NOT NULL,--真实文件相对路径
	THUMBNAIL BYTEA --缩略图
	)','_'||i);

	-- 删除document2表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_2%I','_'||i);
	-- 创建document2表
	EXECUTE format('CREATE TABLE DOCUMENTS_2%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,--文档主键ID
	UUID VARCHAR(36) NOT NULL,--文件挂载ID
	FILEFULLPATH VARCHAR(120) NOT NULL, --真实文件相对路径
	THUMBNAIL BYTEA --缩略图
	)','_'||i);

	-- 删除TRANSITION表
	EXECUTE format('DROP TABLE IF EXISTS TRANSITION%I','_'||i);
	-- 创建TRANSITION表
	EXECUTE format('CREATE TABLE TRANSITION%I(
	TRANSITIONUNIQUEID SERIAL PRIMARY KEY,--迁移主键ID
	TRANSACTIONUUID VARCHAR(36) NOT NULL,--业务记录UUID
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	ACTIVITY VARCHAR(20) NOT NULL,--事件动作
	COMMENTS VARCHAR(200),--评论内容
	OPERATOR VARCHAR(20) NOT NULL,--操作者用户名
	DATECREATED TIMESTAMP NOT NULL --创建日期
	)','_'||i);
	 
   END LOOP;
   
END
$do$;