DO
$do$
BEGIN 

   FOR i IN 0..255 LOOP
	--RAISE NOTICE '%', i;
	-- 删除transaction表
	EXECUTE format('DROP TABLE IF EXISTS TRANSACTION%I','_'||i);
	-- 创建transaction表
	EXECUTE format('CREATE TABLE TRANSACTION%I(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,--业务主键ID
	BARCODE VARCHAR(50),--条形码
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	DATEFINISHED TIMESTAMP,--办结日期
	STATUS VARCHAR(20) NOT NULL,--状态名称
	SITECODE VARCHAR(4) NOT NULL,--站点编码
	BUSINESSCODE VARCHAR(4) NOT NULL, --业务类型编码
	COMMUNITYUNIQUEID INT NOT NULL, --社区ID
	COMPANYUNIQUEID INT NOT NULL,--机构ID
	LOCATIONCODE VARCHAR(30),--位置CDOE
	BATCH INT NOT NULL,--批次号,默认最大1000个批次，每批次最多放3000文件夹。
	UUID VARCHAR(36) NOT NULL, --文件挂载ID
	CODE VARCHAR(15),--上架号
	CREATOR VARCHAR(20) NOT NULL, --录入人用户名
	INDEXNUMBER INT NOT NULL --业务顺序号
	)','_'||i);

	
	-- 删除document1表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_1%I','_'||i);
	-- 创建document1表
	EXECUTE format('CREATE TABLE DOCUMENTS_1%I(
	DOCUMENTUNIQUEID SERIAL PRIMARY KEY,--文档主键ID
	UUID VARCHAR(36) NOT NULL,--文件挂载ID
	DICTIONARYCODE VARCHAR(7) NOT NULL,--材料CODE(数据字典CODE)
	FILEFULLPATH VARCHAR(120) NOT NULL,--真实文件相对路径
	THUMBNAIL BYTEA --缩略图
	)','_'||i);

	-- 删除TRANSITION表
	EXECUTE format('DROP TABLE IF EXISTS TRANSITION%I','_'||i);
	-- 创建TRANSITION表
	EXECUTE format('CREATE TABLE TRANSITION%I(
	TRANSITIONUNIQUEID SERIAL PRIMARY KEY,--迁移主键ID
	TRANSACTIONUUID VARCHAR(36) NOT NULL,--业务记录UUID
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	ACTIVITY VARCHAR(20) NOT NULL,--事件动作
	COMMENTS VARCHAR(200),--评论内容
	OPERATOR VARCHAR(20) NOT NULL,--操作者用户名
	DATECREATED TIMESTAMP NOT NULL --创建日期
	)','_'||i);
	 
   END LOOP;
   
   CREATE TABLE RETURN_TABLE(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,--业务主键ID
	BARCODE VARCHAR(50),--条形码
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	DATEFINISHED TIMESTAMP,--办结日期
	STATUS VARCHAR(20) NOT NULL,--状态名称
	SITECODE VARCHAR(4) NOT NULL,--站点编码
	BUSINESSCODE VARCHAR(4) NOT NULL, --业务类型编码
	COMMUNITYUNIQUEID INT NOT NULL, --社区ID
	COMPANYUNIQUEID INT NOT NULL,--机构ID
	LOCATIONCODE VARCHAR(30),--位置CDOE
	BATCH INT NOT NULL,--批次号,默认最大1000个批次，每批次最多放3000文件夹。
	UUID VARCHAR(36) NOT NULL, --文件挂载ID
	CODE VARCHAR(15),--上架号
	CREATOR VARCHAR(20) NOT NULL, --录入人用户名
	INDEXNUMBER INT NOT NULL, --业务顺序号
	BUSINESSNAME VARCHAR(20) NOT NULL --业务类型名称
 );
  
 
 --文档历史
CREATE TABLE DOCUMENTHISTORY (
	HISTORYUNIQUEID SERIAL PRIMARY KEY,
	TABLEID INT,
	DOCUMENTUNIQUEID INT,
	UUID VARCHAR(36) NOT NULL,--文件挂载ID
	DICTIONARYCODE VARCHAR(7) NOT NULL,--材料CODE(数据字典CODE)
	FILEFULLPATH VARCHAR(120) NOT NULL,--真实文件相对路径
	THUMBNAIL BYTEA, --缩略图
	USERNAME VARCHAR(36),
	DATECREATED TIMESTAMP
);

--公司分类
CREATE TABLE COMPANYCATEGORY (
	CATEGORYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL
);
--地址
CREATE TABLE LOCATIONS (
	LOCATIONUNIQUEID SERIAL PRIMARY KEY,
	CATEGORY VARCHAR(60) NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	CODE VARCHAR(60) NOT NULL
);

--租户
CREATE TABLE TENANT(
	TENANTUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL
);

--系统设置表
CREATE TABLE SYSTEMSETTINGS(
	SETTINGUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,--参数名称
	VALUE VARCHAR(200) NOT NULL,--参数值
	COMMENTS VARCHAR(200)--描述
);

--影像化
CREATE TABLE IMAGING(
	IMAGINGUNIQUEID SERIAL PRIMARY KEY,
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	STATUS VARCHAR(20) NOT NULL,--记录状态
	CREATOR VARCHAR(20) NOT NULL --录入人用户名
);

--社区
CREATE TABLE COMMUNITIES (
	COMMUNITYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYNAME VARCHAR(20) NOT NULL,
	COMMUNITYDESCRIPTION VARCHAR(60),
	TENANTNAME VARCHAR(100) NOT NULL,
	PROVINCE VARCHAR(60) NOT NULL,
	CITY VARCHAR(60),
	DISTRICT VARCHAR(60)
);

--机构
CREATE TABLE COMPANIES (
	COMPANYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYNAME VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(60),
	STOREHOUSENAME VARCHAR(20),--库房名称
	QCSUPPORT BOOLEAN NOT NULL, 
	CATEGORY VARCHAR(20) --车管所/二手车/4S店
);

--用户表
CREATE TABLE USERS (
	USERUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	HASHED VARCHAR(60) NOT NULL,
	ACTIVATED SMALLINT NOT NULL,
	COMPANYNAME VARCHAR(20),
	COMPANYUNIQUEID INT,
	COMMUNITYUNIQUEID INT,
	EMAIL VARCHAR(20),
	PHONE VARCHAR(20),
	FAX VARCHAR(20)
);

--用户配置文件
CREATE TABLE USERPROFILES (
	USERPROFILEUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	TITLE VARCHAR(20),
	PICTURE VARCHAR(40),
	MANAGERUNIQUEID INT,
	CREATEDBY VARCHAR(20),
	CREATORUNIQUEID INT NOT NULL,
	DATECREATED TIMESTAMP,
	DATELASTMODIFIED TIMESTAMP,
	LASTLOGON TIMESTAMP,
	SEX VARCHAR(4),
	EMAIL VARCHAR(20),
	LOCATION VARCHAR(120),
	PHONE VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20)
);

--业务类型
CREATE TABLE BUSINESS (
	BUSINESSUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	CHECKLEVEL VARCHAR(4) NOT NULL,  --审档级别
	CODE VARCHAR(4) NOT NULL, --快捷编码
	UPDATEPLATENUMBER BOOLEAN,
	UPLOADPICTURE BOOLEAN
);

--数据字典
CREATE TABLE DATADICTIONARY (
	DICTIONARYUNIQUEID SERIAL PRIMARY KEY,
	ITEMTYPE SMALLINT NOT NULL,      --数据项类别 1-号牌种类 2-材料名称
	ITEMNAME VARCHAR(51) NOT NULL,   --数据项名称
	CODE VARCHAR(7) NOT NULL       --快捷编码
);

--业务类型对应的材料名称（必录项）
CREATE TABLE BUSINESSITEMS (
	ITEMUNIQUEID SERIAL PRIMARY KEY,
	BUSINESSCODE VARCHAR(4) NOT NULL,
	DICTIONARYCODE VARCHAR(7) NOT NULL
);

--业务类型对应的材料名称（选录项）
CREATE TABLE BUSINESSITEMS2 (
	ITEMUNIQUEID SERIAL PRIMARY KEY,
	BUSINESSCODE VARCHAR(4) NOT NULL,
	DICTIONARYCODE VARCHAR(7) NOT NULL
);

--机构-业务类型
CREATE TABLE COMPANYBUSINESSES (
	CBUNIQUEID SERIAL PRIMARY KEY,
	COMPANYUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--用户-业务类型
CREATE TABLE USERBUSINESSES (
	UBUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--上架号
CREATE TABLE FRAMENUMBER (
	FRAMEUNIQUEID SERIAL PRIMARY KEY,
	STOREHOUSENAME VARCHAR(20) NOT NULL, --库房名称
	FRAMECODE INT,--密集架号
	MAXCOLUMN INT NOT NULL,
	MAXROW INT NOT NULL,
	CELLCODE INT,--单元格号
	COL INT NOT NULL,
	ROW INT NOT NULL,
	VIN VARCHAR(50),--车辆识别代码
	CODE VARCHAR(20),--上架号，例如014-002-003-001(密集架号-列-行-文件夹序号）
	MAXFOLDER INT --单元格内最大文件夹数
);

 
 
--站点
CREATE TABLE SITE (
	SITEUNIQUEID SERIAL PRIMARY KEY,
	SITENAME VARCHAR(20) NOT NULL,--站点名
	SITETYPE VARCHAR(20) NOT NULL,--站点类型
	HOSTADDR VARCHAR(50) NOT NULL,--主机地址
	PORT SMALLINT,--端口号
	DEFAULTREMOTEDIRECTORY VARCHAR(50), --默认目录
	USERNAME VARCHAR(20), --服务用户名
	PASSWORD VARCHAR(50), --密码
	MODE VARCHAR(10), --传输模式
	CHARSET VARCHAR(10), --字符集
	RUNNINGSTATUS SMALLINT NOT NULL, --运行状态 1运行 0停止
	CODE VARCHAR(7) NOT NULL --快捷编码
);

--站点容量
CREATE TABLE SITECAPACITY (
	SITECAPACITYUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	CAPACITY BIGINT,
	USEDSPACE BIGINT,
	UPDATETIMEMILLIS BIGINT,
	UNIT VARCHAR(4),
	UNITNUMBER VARCHAR(10),
	MAXBATCH INT, -- 最大批次数
	MAXBUSINESS INT -- 每批次内最大业务数
);

--站点内文件个数
CREATE TABLE SITEFOLDER (
	SITEFOLDERUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	BATCHCOUNT INT, --批次增长数
	BUSINESSCOUNT INT --业务数量
	
);
 
--社区-站点
CREATE TABLE COMMUNITYSITES (
	CSUNIQUEID SERIAL NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	FOREIGN KEY (COMMUNITYUNIQUEID)
		REFERENCES COMMUNITIES (COMMUNITYUNIQUEID),
	FOREIGN KEY (SITEUNIQUEID)
		REFERENCES SITE (SITEUNIQUEID),
	PRIMARY KEY (CSUNIQUEID, COMMUNITYUNIQUEID, SITEUNIQUEID)
);
--消息系统
CREATE TABLE MESSAGES (
	MESSAGEUNIQUEID SERIAL PRIMARY KEY,
	SUBJECT VARCHAR(50) NOT NULL,--标题
	CONTENT VARCHAR(200) NOT NULL,--内容
	MATEDATA VARCHAR(200) NOT NULL,--元数据
	CREATORUNIQUEID INT NOT NULL,--创建者ID
	DATECREATED TIMESTAMP, -- 创建时间
	SENTTIMES SMALLINT NOT NULL,--已发送次数
	REMINDERFREQUENCYID INT NOT NULL, -- 发送频率ID
	DELETED SMALLINT NOT NULL
);
--消息接收者
CREATE TABLE MESSAGERECIPIENT (
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收方ID
	RECIPIENTNAME VARCHAR(50) NOT NULL,--接收方名称
	RECIPIENTTYPE SMALLINT NOT NULL, --接收方类别
	MESSAGEUNIQUEID INT NOT NULL -- 消息ID
);
--提醒频率
CREATE TABLE REMINDERFREQUENCY (
	FREQUENCYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	FREQUENCY SMALLINT NOT NULL, -- 1-每天 7-每周
	ENABLED SMALLINT NOT NULL,--1-启用 0禁用
	STARTINGTIME TIMESTAMP,--起始时间
	ENDINGTIME TIMESTAMP -- 结束时间
);
--通知表
CREATE TABLE NOTIFICATIONS (
	NOTIFICATIONUNIQUEID SERIAL PRIMARY KEY,
	MESSAGEUNIQUEID INT NOT NULL, --消息ID
	WARNING BOOLEAN NOT NULL,--警告级别
	USERUNIQUEID INT NOT NULL,--接收者用户名
	VIEWNAME VARCHAR(20) NOT NULL,--区分相同接收者不同的视图
	SENDTIME TIMESTAMP NOT NULL,
	MARKEDASREAD BOOLEAN NOT NULL--标识已读
);

--质检队列
CREATE TABLE QUEUE_1 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。质检只能取本社区和本机构的记录
);
--审档队列
CREATE TABLE QUEUE_2 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。普通审档只能取本社区和本机构的记录
);
--确认审档队列
CREATE TABLE QUEUE_3 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。确认审档只能取本社区和本机构的记录
);
--角色表
CREATE TABLE ROLE (
	ROLEUNIQUEID SERIAL PRIMARY KEY,
	ROLENAME VARCHAR(20) NOT NULL,
	ROLETYPE VARCHAR(10) NOT NULL
);
--权限表
CREATE TABLE PERMISSION (
	PERMISSIONUNIQUEID SERIAL PRIMARY KEY,
	CATEGORYUNIQUEID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);
--权限类别表
CREATE TABLE PERMISSIONCATEGORY (
	CATEGORYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL
);
--用户与角色关系表
CREATE TABLE ROLEMEMBER (
	ROLEMEMBERUNIQUEID SERIAL NOT NULL,
	USERUNIQUEID INT NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	FOREIGN KEY (USERUNIQUEID)
		REFERENCES USERS (USERUNIQUEID),
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	PRIMARY KEY (ROLEMEMBERUNIQUEID, USERUNIQUEID, ROLEUNIQUEID)
);
--角色与权限关系表
CREATE TABLE ROLERIGHT (
	ROLERIGHTUNIQUEID SERIAL NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	PERMISSIONUNIQUEID INT NOT NULL,
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	FOREIGN KEY (PERMISSIONUNIQUEID)
		REFERENCES PERMISSION (PERMISSIONUNIQUEID),
	PRIMARY KEY (ROLERIGHTUNIQUEID, ROLEUNIQUEID, PERMISSIONUNIQUEID)
);

--批改建议
CREATE TABLE FEEDBACK (
	FEEDBACKUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,--用户名
	SUGGESTION VARCHAR(200) NOT NULL,--批改意见
	FREQUENCY INT NOT NULL--出现频率
);
--业务状态
CREATE TABLE BUSINESSSTATE (
	STATEUNIQUEID SERIAL PRIMARY KEY,
	CODE VARCHAR(60) NOT NULL,
	NAME VARCHAR(20) NOT NULL
);
--内嵌服务器
CREATE TABLE EMBEDDEDSERVER (
	SERVERUNIQUEID SERIAL PRIMARY KEY,
	SERVERNAME VARCHAR(60) NOT NULL,--站点名
	SERVERTYPE VARCHAR(60) NOT NULL,--站点类型
	HOSTADDR VARCHAR(60),--主机地址
	PORT SMALLINT,--端口号
	RUNNINGSTATUS SMALLINT NOT NULL, --运行状态 1运行 0停止
	CODE VARCHAR(7) NOT NULL, --快捷编码
	JKS VARCHAR(120),--JKS证书路径
	JKSPASS VARCHAR(120),--JKS证书密码
	USERPROPERTIES VARCHAR(120)--用户属性文件路径
);
--系统日志表
CREATE TABLE SYSTEMLOG (
	LOGUNIQUEID SERIAL PRIMARY KEY,
	LOGTYPE VARCHAR(20),--日志类型
	USERNAME VARCHAR(20),--操作者
	IPADDR VARCHAR(60),--操作者IP
	MODULE VARCHAR(60),--模块ID
	MESSAGE VARCHAR(200),--详细内容
	EXCEPTION VARCHAR(250),--异常
	DATECREATED TIMESTAMP NOT NULL--创建日期
);
--车辆信息
CREATE TABLE CARS (
	CARUNIQUEID SERIAL PRIMARY KEY,--业务主键ID
	BARCODE VARCHAR(50),--条形码
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL--车辆识别代码
);
 
   
END
$do$;