DO
$DO$
BEGIN 
	
   FOR I IN 0..255 LOOP
	--RAISE NOTICE '%', I;
	-- 删除TRANSACTION表
	EXECUTE FORMAT('DELETE FROM TRANSACTION%I','_'||I);
	-- 删除DOCUMENT1表
	EXECUTE FORMAT('DELETE FROM DOCUMENTS_1%I','_'||I);
	 
      
   END LOOP;
END
$DO$;