DO
$do$
BEGIN 

	DROP FUNCTION IF EXISTS INSERT_DATA();
	DROP FUNCTION IF EXISTS CREATE_TABLES();
	DROP FUNCTION IF EXISTS SPLITUP_LARGE_TABLE();
	DROP FUNCTION IF EXISTS CREATE_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR);
	DROP FUNCTION IF EXISTS SEARCH_BY_KEYWORD_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
	DROP FUNCTION IF EXISTS SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN_PAGINGCOUNT(LIMIT2 INT,PLATETYPE VARCHAR,PLATENUMBER VARCHAR,VIN VARCHAR,COMMUNITYNAME VARCHAR);
	DROP FUNCTION IF EXISTS SEARCH_BY_KEYWORD(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
	DROP FUNCTION IF EXISTS SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN(LIMIT2 INT,OFFSET2 INT,PLATETYPE VARCHAR,PLATENUMBER VARCHAR,VIN VARCHAR,COMMUNITYNAME VARCHAR);

	
   FOR i IN 0..255 LOOP
	--RAISE NOTICE '%', i;
	-- 删除transaction表
	EXECUTE format('DROP TABLE IF EXISTS TRANSACTION%I','_'||i);
	-- 删除document1表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_1%I','_'||i);
	-- 删除document2表
	EXECUTE format('DROP TABLE IF EXISTS DOCUMENTS_2%I','_'||i);
	-- 删除document2表
	EXECUTE format('DROP TABLE IF EXISTS TRANSITION%I','_'||i);
      
   END LOOP;
   
    DROP TABLE IF EXISTS RETURN_TABLE;
    DROP TABLE IF EXISTS MESSAGES;
	DROP TABLE IF EXISTS MESSAGERECIPIENT;
	DROP TABLE IF EXISTS REMINDERFREQUENCY;
	DROP TABLE IF EXISTS SENDDETAILS;
	DROP TABLE IF EXISTS COMMUNITYSITES;
	DROP TABLE IF EXISTS COMMUNITYTENANTS;
	DROP TABLE IF EXISTS TENANTS;
	DROP TABLE IF EXISTS COMPANYBUSINESSES;
	DROP TABLE IF EXISTS USERBUSINESSES;
	DROP TABLE IF EXISTS BUSINESSITEMS;
	DROP TABLE IF EXISTS DATADICTIONARY;
	DROP TABLE IF EXISTS AUDITS;
	DROP TABLE IF EXISTS QUEUE_3;
	DROP TABLE IF EXISTS QUEUE_2;
	DROP TABLE IF EXISTS QUEUE_1;
	DROP TABLE IF EXISTS SITEFOLDER;
	DROP TABLE IF EXISTS SITECAPACITY;
	DROP TABLE IF EXISTS SITE;
	DROP TABLE IF EXISTS BUSINESS; 
	DROP TABLE IF EXISTS ROLERIGHT;
	DROP TABLE IF EXISTS ROLEMEMBER;
	DROP TABLE IF EXISTS PERMISSIONCATEGORY;
	DROP TABLE IF EXISTS PERMISSION;
	DROP TABLE IF EXISTS ROLE;
	DROP TABLE IF EXISTS USERPROFILES;
	DROP TABLE IF EXISTS USERS;
	DROP TABLE IF EXISTS PORTFOLIO;
	DROP TABLE IF EXISTS FILEBOX;
	DROP TABLE IF EXISTS DENSEFRAME;
	DROP TABLE IF EXISTS STOREHOUSE;
	DROP TABLE IF EXISTS COMPANIES;
	DROP TABLE IF EXISTS COMMUNITIES;
	DROP TABLE IF EXISTS FRAMENUMBER;
	DROP TABLE IF EXISTS IMAGING;
	DROP TABLE IF EXISTS SYSTEM_SETTINGS;
	DROP TABLE IF EXISTS COMMONPROBLEMS;
   
END
$do$;