DO
$DO$
BEGIN 
	
   FOR I IN 0..255 LOOP
	--RAISE NOTICE '%', I;
	-- 删除TRANSACTION表
	EXECUTE FORMAT('DELETE FROM TRANSACTION%I','_'||I);
	-- 删除DOCUMENT1表
	EXECUTE FORMAT('DELETE FROM DOCUMENTS_1%I','_'||I);
	-- 删除DOCUMENT2表
	EXECUTE FORMAT('DELETE FROM DOCUMENTS_2%I','_'||I);
	-- 删除DOCUMENT2表
	EXECUTE FORMAT('DELETE FROM TRANSITION%I','_'||I);
      
   END LOOP;
 
   
    DELETE FROM MESSAGES;
	DELETE FROM MESSAGERECIPIENT;
	DELETE FROM REMINDERFREQUENCY;
	DELETE FROM NOTIFICATIONS;
	DELETE FROM QUEUE_3;
	DELETE FROM QUEUE_2;
	DELETE FROM QUEUE_1;
	DELETE FROM QUEUE_1;
END
$DO$;