DROP FUNCTION IF EXISTS FIND_BY_XXX(COMMUNITYNAME VARCHAR);
CREATE OR REPLACE FUNCTION FIND_BY_XXX(COMMUNITYNAME VARCHAR) RETURNS SETOF RETURN_TABLE AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';

	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE LEFT JOIN DOCUMENTS_1_'||I||' AS C ON C.UUID=A.UUID WHERE C.DICTIONARYCODE=''XXX'' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE LEFT JOIN DOCUMENTS_1_255 AS C ON C.UUID=A.UUID WHERE C.DICTIONARYCODE=''XXX''';
   
   --RAISE NOTICE '%', EX_SQL;
   RETURN QUERY EXECUTE EX_SQL;
END
$BODY$
LANGUAGE PLPGSQL;
SELECT * FROM FIND_BY_XXX('DL');