DROP FUNCTION IF EXISTS GET_TABLE_INDEX(VIN VARCHAR);
CREATE OR REPLACE FUNCTION GET_TABLE_INDEX(VIN VARCHAR) RETURNS INTEGER AS
$BODY$
DECLARE
   L INTEGER := 0;
   STRARRAY VARCHAR[];
   NUM INTEGER := 0;
BEGIN 

   L := CHAR_LENGTH(VIN);
 
   STRARRAY := STRING_TO_ARRAY(VIN, NULL);

   FOR I IN 1..L LOOP
     NUM := NUM + ASCII(STRARRAY[I]);
      
   END LOOP;

   NUM := NUM % 256;

   RAISE NOTICE '%', NUM;

   RETURN NUM;
 
END
$BODY$
LANGUAGE PLPGSQL;

SELECT * FROM GET_TABLE_INDEX('ASDF');