DO
$do$
BEGIN 
	
     --插入系统用户
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('system','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'',0,0,'sys1@max.com','047-5831-01',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (1,'系统管理员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','车','管');

	
	--插入系统权限类别
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('登录类别');--A 1
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('个人配置');--B 2
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理用户');--C 3
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理角色');--D 4
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理权限');--E 5
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理机构');--F 6
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理社区');--G 7
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('高拍仪');  --H 8
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理查询');--J 9
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理站点');--K 10
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('广播消息');--L 11
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('数据字典');--M 12
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('业务类型');--N 13
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理范围');--O 14
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理库房');--P 15
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理服务器');--Q 16
	
	
	--插入所有权限
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A1','管理员','管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A2','前台','前台用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A3','质检','质检用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A4','审档','审档用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A5','查询','数据查询用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A6','上架下架','上架下架用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A7','确认审档','只对一级审档业务确认审档');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A8','影像化管理员','影像化管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A9','影像化录入','影像化录入');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A10','影像化质检','影像化质检');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A11','最终审档','最终审档');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B1','更改个人资料','更改个人资料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B2','更改密码','更改密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C1','创建','创建用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C2','编辑','编辑用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C3','删除','删除用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C4','查看','查看用户列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C5','分配角色','为用户分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C6','分配业务','为用户分配业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C7','重置密码','为用户重置密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D1','创建','创建角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D2','编辑','编辑角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D3','删除','删除角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D4','分配用户','为角色分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D5','设置权限','为角色分配权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D6','查看','查看角色列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E1','分配角色','为权限分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E2','编辑','编辑权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E3','查看','查看权限列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F1','创建','创建机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F2','编辑','编辑机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F3','删除','删除机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F4','分配用户','为机构分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F5','管理库房','管理库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F6','查看','查看机构列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F7','设置','设置业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G1','创建','创建社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G2','编辑','编辑社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G3','删除','删除社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G4','分配机构','分配机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G5','查看','查看社区列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G6','分配站点','为社区分配站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'H1','更改高拍仪','更改高拍仪');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'J1','删除','删除业务记录及其所有原文');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K1','创建','创建站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K2','编辑','编辑站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K3','删除','删除站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K4','查看','查看站点列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K5','分配社区','为站点分配社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K6','操作','对站点进行启动/停止/测试连接操作');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L1','发送消息','发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L2','查看','查看消息列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L3','设置','设置定时发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L4','删除','删除消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M1','创建','创建数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M2','编辑','编辑数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M3','删除','删除数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M4','查看','查看数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N1','创建','创建业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N2','编辑','编辑业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N3','删除','删除业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N4','查看','查看业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N5','设置','设置业务材料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'O1','社区范围内','社区管理员既可以管社区也可以管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'O2','机构范围内','机构管理员只允许管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P1','创建','创建库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P2','编辑','编辑库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P3','删除','删除库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P4','查看','查看库房列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P5','分配机构','为库房分配一个机构（通常机构是车管所）');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P6','管理密集架','管理密集架');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(16,'Q1','查看','查看服务器列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(16,'Q2','编辑','编辑服务器配置信息');
	
	
	--插入全部角色
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('系统管理员', '系统内置');	--1
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('前台', '自定义');	--2
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('质检', '自定义');	--3
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('审档', '自定义');	--4
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('查询', '自定义');	--5
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('上架下架', '自定义');	--6
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('确认审档', '自定义');	--7
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化管理员', '自定义');	--8
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化录入', '自定义');	--9
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化质检', '自定义');	--10
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连社区管理员', '自定义');	--11
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连车管所管理员', '自定义');	--12
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('庄河社区管理员', '自定义');	--13
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('庄河车管所管理员', '自定义');	--14
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连二手车管理员', '自定义');	--15
 	
 	
 	--插入系统管理员权限
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,11);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,12);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,13);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,14);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,15);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,16);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,17);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,18);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,19);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,20);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,21);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,22);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,23);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,24);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,25);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,26);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,27);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,28);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,29);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,30);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,31);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,32);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,33);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,34);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,35);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,36);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,37);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,38);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,39);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,40);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,41);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,42);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,43);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,44);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,45);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,46);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,47);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,48);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,49);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,50);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,51);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,52);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,53);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,54);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,55);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,56);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,57);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,58);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,59);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,60);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,61);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,62);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,65);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,66);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,67);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,68);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,69);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,70);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,71);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,72);
	
	--插入system用户角色关系
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(1,1); --为system用设置角色
	
	
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0101-注册登记','无','0101');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0201-变更机动车所有人姓名/名称','无','0201');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0202-变更共同所有人姓名/名称','无','0202');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0203-变更使用性质','无','0203');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0204-更换发动机','无','0204');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0205-更换车身/车架','无','0205');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0206-变更车身颜色','无','0206');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0207-更换整车','无','0207');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0208-住所迁出车管所管辖区域','无','0208');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0209-重新打刻发动机号码','无','0209');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0210-重新打刻车辆识别','无','0210');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0211-变更身份证明名称/号码','无','0211');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0214-加装残疾人操纵辅助装备','无','0214');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0215-拆除残疾人操纵辅助装置','无','0215');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0216-变更登记','无','0216');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0301-转移登记','无','0301');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0302-转出/注销恢复','无','0302');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0303-解除监管','无','0303');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0401-抵押登记','无','0401');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0501-解除抵押登记','无','0501');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0601-质押备案','无','0601');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0701-解除质押备案','无','0701');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0801-补领登记证书','无','0801');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('0901-换领登记证书','无','0901');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('1001-申领登记证书','无','1001');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('1101-登记事项更正','无','1101');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('1201-补建机动车档案','无','1201');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('1301-转入机动车','无','1301');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('1401-影像化档案信息更正','无','1401');
	
	
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注册、转移、注销登记转入申请表》原件','F001');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有人身份证明复印件','F002');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车来历证明原件或复印件','F003');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆购置税完税证明副联原件','F004');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车查验记录表原件','F005');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车标准照片','F006');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车识别代号拓印膜','F007');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进口车五部位照片','F008');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其他证明、凭证的原件或者复印件','F009');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车变更登记备案申请表》原件','F010');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更证明','F011');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行驶证原件','F012');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更前机动车所有人身份证明','F013');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'共同所有的公证证明或证明夫妻关系的居民户口簿和结婚证','F014');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更使用性质证明','F015');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车安全技术检验合格证明','F016');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术鉴定证明或公安机关发还证明','F017');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现合格证','F018');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原合格证','F019');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'操纵辅助装置加装合格证明','F020');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现机动车所有人身份证明','F021');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车所有人身份证明','F022');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有权转移证明','F023');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车抵押登记或者质押备案申请表','F024');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押权人身份证明','F025');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押合同','F026');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》','F027');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明','F028');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车牌证申请表','F029');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民检察院、行政执法部门未得到登记证书证明','F030');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民检察院、机动车勘误登记申请表','F031');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'书面报告','F032');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准补建机动车档案文件','F033');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'该机动车在系统中的所有记录信息','F034');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'核对公函','F035');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'影像化档案信息更正申请表','F036');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'转出注销相关资料','F037');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'解除监管证明书','F038');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'合格证','F039');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料','F040');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其它资料','F041');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进口车五部位qweqw照片','F042');

	----数据字典 1:号牌种类
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'1-大型汽车','HPZL01');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'2-小型汽车','HPZL02');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'3-使馆汽车','HPZL03');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'4-领馆汽车','HPZL04');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'5-境外汽车','HPZL05');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'6-外籍汽车','HPZL06');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'7-普通摩托车','HPZL07');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'8-轻便摩托车','HPZL08');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'9-使馆摩托车','HPZL09');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'10-领馆摩托车','HPZL10');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'11-境外摩托车','HPZL11');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'12-外籍摩托车','HPZL12');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'13-低速车','HPZL13');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'14-拖拉机','HPZL14');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'15-挂车','HPZL15');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'16-教练汽车','HPZL16');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'17-教练摩托车','HPZL17');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'18-试验汽车','HPZL18');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'19-试验摩托车','HPZL19');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'20-临时入境汽车','HPZL20');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'21-临时入境摩托车','HPZL21');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'22-临时行使车','HPZL22');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'23-警用汽车','HPZL23');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'24-警用摩托','HPZL24');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'25-原农机号牌','HPZL25');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'26-香港入出境车','HPZL26');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'27-澳门入出境车','HPZL27');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'28-大型新能源汽车','HPZL28');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'29-小型新能源汽车','HPZL29');
	
	--材料名称
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注册、转移、注销登记转入申请表》原件','CL01');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'发动机号码拓印膜','CL44');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'盗抢汽车立案证明复印件','CL45');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'介绍信原件','CL46');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其它证明、凭证的原件或者复印件','CL47');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'拍卖成交确认书复印件','CL48');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'警车号牌审批表原件','CL49');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关事项变更证明复印件','CL50');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆购置税完税证明副联原件','CL07');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'申请表','CL33');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车业务流程单','CL51');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《判决书》原件或者复印件','CL52');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'监销人和销毁人签字的销毁记录原件','CL53');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'公安交通管理撤销决定书原件','CL54');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'影像化档案信息更正申请表','CL38');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其它资料','CL32');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联原件或复印件','CL55');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术参数表','CL56');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'校车使用许可复印件','CL57');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车变更登记备案申请表','CL18');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'身体条件证明','CL58');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车的来历证明原件或复印件','CL21');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车勘误登记申请表','CL23');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《中华人民共和国海关监管车辆解除监管证明书》原件','CL59');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》;人民检察院、行政执法部门未得到登记证书证明','CL12');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车牌证申请表','CL24');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联原件或者复印件','CL60');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《报废汽车回收证明》复印件','CL61');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'委托书原件','CL62');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《裁定书》复印件','CL63');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车所有人身份证明复印件','CL64');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'中国海关等部门准许入境的凭证复印件','CL65');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料记录','CL66');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'询问记录','CL67');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'出境证明复印件','CL68');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'仲裁机构出具的《仲裁裁决书》原件或复印件','CL69');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关证明或手续原件','CL70');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'承诺书原件','CL71');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原登记证书原件','CL72');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'档案查询公函原件','CL73');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车船税完税证明复印件','CL74');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位注销证明复印件','CL75');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车驾驶证原件','CL76');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车所有人身份证明','CL40');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车交通事故责任强制保险凭证第三联原件','CL77');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行驶证原件','CL37');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'登记证书原件','CL78');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车抵押登记或者质押备案申请表》原件','CL79');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更证明','CL05');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车安全技术检验合格证明','CL17');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车来历证明复印件','CL80');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'共同所有的公证证明或证明夫妻关系的居民户口簿和结婚证','CL14');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车查验记录表原件','CL19');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现机动车所有人身份证明','CL36');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'拓印膜','A043');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进口车5部位照片','CL29');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'合格证','CL15');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原合格证','CL39');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押权人身份证明','CL09');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'该机动车在系统中的所有记录信息','CL13');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'公函原件','CL81');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车标准照片','CL82');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《裁定书》复印件','CL83');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'安全技术检验合格证明','CL02');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'未得到登记证书的证明原件','CL84');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'依法收缴的法律文书复印件','CL85');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《判决书》复印件','CL86');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'核对公函','CL16');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位吊销证明复印件','CL87');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'经办人工作证明复印件','CL88');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车业务流程记录单','CL89');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车抵押登记或者质押备案申请表','CL22');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'代办人身份证明复印件','CL90');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'退车证明原件','CL91');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'驾驶技能准考证明','CL92');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准补建机动车档案文件','CL30');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'海关批准的转让证明原件','CL93');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《判决书》原件或复印件','CL94');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交通强险第三联原件','CL95');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'调查取证材料原件','CL96');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押权人身份证明复印件','CL97');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《仲裁裁决书》复印件','CL98');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术鉴定证明复印件','CL99');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'询问笔录原件','CL100');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'解体照片','CL101');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车识别代号拓印膜','CL102');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行政处罚决定书复印件','CL103');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《居民户口簿》复印件','CL104');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'解除监管证明书','CL28');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注册、转移、注销登记或转入申请表》复印件','CL105');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'罚没款收据复印件','CL106');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'灭失证明原件','CL107');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车档案补录档案更正申请表》','CL108');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行政强制措施凭证（滞留车辆）原件','CL109');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明','CL10');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现合格证','CL35');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有权转移证明','CL25');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车安全技术检验合格证明原件','CL110');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《调解书》原件或者复印件','CL111');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆使用性质证明原件','CL112');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'嫌疑车辆移交清单原件','CL113');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'操纵辅助装置加装合格证明','CL06');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料','CL20');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现机动车所有人身份证明复印件','CL114');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车档案','CL115');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车整车出厂合格证明复印件','CL116');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联原件','CL117');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'报废机动车回收证明原件','CL118');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'受案登记表复印件','CL119');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《判决书》复印件','CL120');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'书面报告原件','CL121');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车变更登记备案申请表》原件','CL122');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关证明或者手续原件','CL123');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'重复核对报告表复印件','CL124');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'驾驶人考试成绩单','CL125');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'公安机关发还证明复印件','CL126');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其资它料','CL127');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料目录','CL128');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更前机动车所有人身份证明','CL03');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准文件原件','CL129');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进（出）境领（销）牌照通知书原件','CL130');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《结婚证》复印件','CL131');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'核对公函原件','CL132');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明复印件','CL133');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准补建机动车档案的文件原件','CL134');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车被盗抢证明》原件或者复印件','CL135');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'驾驶培训记录单','CL136');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》','CL11');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押合同','CL08');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车登记证明复印件','CL137');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其他资料','CL31');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'发动机号码拓印膜原件','CL138');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'办案单位公函原件','CL139');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术鉴定证明或公安机关发还证明','CL27');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车牌证申请表》原件','CL140');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'两人以上共同所有的公证证明复印件','CL141');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《裁定书》原件或复印件','CL142');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更使用性质证明','CL04');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'身份证明复印件(暂住证)','CL143');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车管所书面记载调查情况','CL144');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'转出注销相关资料','CL41');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《调解书》复印件','CL145');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有人身份证明复印件','CL26');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'有关证据','CL146');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'科研、定型试验书面申请原件','CL147');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车驾驶人档案目录','CL148');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《裁定书》原件或者复印件','CL149');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》复印件','CL150');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押合同原件或者复印件','CL151');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联复印件','CL152');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注销证明书》原件','CL153');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位注销查询卡复印件','CL154');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关部门证明原件','CL155');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《影像化档案信息更正申请表》原件','CL156');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车识别代号拓印膜原件','CL157');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其他证明、凭证的原件或者复印件','CL158');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'中文翻译文本原件','CL159');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'书面报告','CL34');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'肢体残疾人操纵辅助装置加装合格证明复印件','CL160');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《调解书》原件或复印件','CL161');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'转出注销恢复证明原件','CL162');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'控购证明原件','CL163');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《协助执行通知书》原件','CL164');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'待销毁的机动车档案清单','CL165');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位吊销查询卡复印件','CL166');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车被盗抢证明》原件或复印件','CL167');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车来历证明原件或复印件者','CL168');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《临时入境机动车号牌、行驶证申请表》原件','CL169');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车勘误登记申请表》原件','CL170');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆照片','A042');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《申请恢复机动车登记业务审批表》原件','CL171');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车驾驶证申请表','CL172');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'有组织的旅游、比赛以及其他交往活动的证明原件','CL173');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'仲裁机构出具的《仲裁裁决书》原件或者复印件','CL174');
	
	
	 --业务状态
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B1','待录入');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B2','待上架');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B3','已入库');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B4','待审核');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B5','待复审');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B6','已归档');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B7','待质检');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B8','待查看');--影像化检测
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B9','待提档');--影像化检测
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B10','待归档');--影像化检测
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B11','完成');--影像化检测
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B12','调档');--下架
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B13','转出');--下架
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B14','待补充');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B15','质检不合格');
	INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B16','审核不合格');
    INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B17','确认审核不合格');
    INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B18','待入库');
    INSERT INTO BUSINESSSTATE(CODE,NAME) VALUES('B19','待终审');
    
    --机构分类
    INSERT INTO COMPANYCATEGORY(NAME) VALUES('车管所');
    INSERT INTO COMPANYCATEGORY(NAME) VALUES('二手车');
    INSERT INTO COMPANYCATEGORY(NAME) VALUES('4S店');
    
    --高拍仪
   	INSERT INTO SYSTEMSETTINGS(NAME,VALUE,COMMENTS) VALUES ('高拍仪','无锡华通H6-1',''); --默认使用无锡华通H6-1
   	
   	
END
$do$;