DROP FUNCTION IF EXISTS INSERT_DATA();
DROP FUNCTION IF EXISTS CREATE_SEARCH(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
DROP TABLE IF EXISTS RETURN_TABLE;
CREATE TABLE RETURN_TABLE(
	TRANSACTIONUNIQUEID SERIAL PRIMARY KEY,--业务主键ID
	BARCODE VARCHAR(50),--条形码
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	DATEFINISHED TIMESTAMP,--办结日期
	STATUS VARCHAR(20) NOT NULL,--状态名称
	SITECODE VARCHAR(4) NOT NULL,--站点编码
	BUSINESSCODE VARCHAR(4) NOT NULL, --业务类型编码
	COMMUNITYUNIQUEID INT NOT NULL, --社区ID
	COMPANYUNIQUEID INT NOT NULL,--机构ID
	LOCATIONCODE VARCHAR(30),--位置CDOE
	BATCH INT NOT NULL,--批次号,默认最大1000个批次，每批次最多放3000文件夹。
	UUID VARCHAR(36) NOT NULL, --文件挂载ID
	CODE VARCHAR(15),--上架号
	CREATOR VARCHAR(20) NOT NULL, --录入人用户名
	INDEXNUMBER INT NOT NULL, --业务顺序号
	BUSINESSNAME VARCHAR(20) NOT NULL --业务类型名称
 );

DROP FUNCTION IF EXISTS CREATE_TABLES();
CREATE OR REPLACE FUNCTION CREATE_TABLES() RETURNS SETOF integer AS
$BODY$
BEGIN

DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS MESSAGERECIPIENT;
DROP TABLE IF EXISTS REMINDERFREQUENCY;
DROP TABLE IF EXISTS SENDDETAILS;
DROP TABLE IF EXISTS COMMUNITYSITES;
DROP TABLE IF EXISTS COMMUNITYTENANTS;
DROP TABLE IF EXISTS TENANTS;
DROP TABLE IF EXISTS COMPANYBUSINESSES;
DROP TABLE IF EXISTS USERBUSINESSES;
DROP TABLE IF EXISTS BUSINESSITEMS;
DROP TABLE IF EXISTS DATADICTIONARY;
DROP TABLE IF EXISTS QUEUE_3;
DROP TABLE IF EXISTS QUEUE_2;
DROP TABLE IF EXISTS QUEUE_1;
--DROP TABLE IF EXISTS SITEFOLDER;
--DROP TABLE IF EXISTS SITECAPACITY;
--DROP TABLE IF EXISTS SITE;
DROP TABLE IF EXISTS BUSINESS; 
DROP TABLE IF EXISTS ROLERIGHT;
DROP TABLE IF EXISTS ROLEMEMBER;
DROP TABLE IF EXISTS PERMISSIONCATEGORY;
DROP TABLE IF EXISTS PERMISSION;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USERPROFILES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FRAMENUMBER;
DROP TABLE IF EXISTS COMPANIES;
DROP TABLE IF EXISTS COMMUNITIES;
DROP TABLE IF EXISTS IMAGING;
DROP TABLE IF EXISTS IMAGING;
DROP TABLE IF EXISTS SYSTEM_SETTINGS;--系统设置
DROP TABLE IF EXISTS CORRECTINGSUGGESTIONS;--批改建议
DROP TABLE IF EXISTS BUSINESSSTATE;--业务状态
DROP TABLE IF EXISTS EMBEDDEDSERVER;--内嵌服务器
DROP TABLE IF EXISTS SYSTEMLOG;--系统日志表
DROP TABLE IF EXISTS NOTIFICATIONS;--通知表

--系统设置表
CREATE TABLE SYSTEM_SETTINGS(
	SETTINGUNIQUEID SERIAL PRIMARY KEY,
	K VARCHAR(20) NOT NULL,--键
	V VARCHAR(20) NOT NULL--值
);

--影像化
CREATE TABLE IMAGING(
	IMAGINGUNIQUEID SERIAL PRIMARY KEY,
	PLATETYPE VARCHAR(20) NOT NULL,--号牌种类
	PLATENUMBER VARCHAR(20) NOT NULL,--号牌号码
	VIN VARCHAR(50) NOT NULL,--车辆识别代码
	DATECREATED TIMESTAMP NOT NULL,--创建日期
	DATEMODIFIED TIMESTAMP,--最近修改日期
	STATUS VARCHAR(20) NOT NULL,--记录状态
	CREATOR VARCHAR(20) NOT NULL --录入人用户名
);

--社区
CREATE TABLE COMMUNITIES (
	COMMUNITYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYNAME VARCHAR(20) NOT NULL,
	COMMUNITYDESCRIPTION VARCHAR(60),
	GROUPID INT NOT NULL,
	LEVEL SMALLINT NOT NULL
);

--机构
CREATE TABLE COMPANIES (
	COMPANYUNIQUEID SERIAL PRIMARY KEY,
	COMMUNITYUNIQUEID INT NOT NULL,
	COMPANYNAME VARCHAR(20) NOT NULL,
	PROVINCE VARCHAR(20) NOT NULL, -- 省份
	CITY VARCHAR(20),  --地级市
	DISTRICT VARCHAR(20), --市、县级市
	ADDRESS VARCHAR(60),
	HASSTOREHOUSE SMALLINT NOT NULL, --是否有库房 1：有 0：没有
	STOREHOUSENAME VARCHAR(20),--库房名称
	IGNORECHECKER SMALLINT NOT NULL, 	  --1-忽略质检（前台可以直接提交到审档队列），0-不忽略
	CATEGORY VARCHAR(20) --车管所/二手车/4S店
);

--用户表
CREATE TABLE USERS (
	USERUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	HASHED VARCHAR(60) NOT NULL,
	ACTIVATED SMALLINT NOT NULL,
	COMPANYNAME VARCHAR(20),
	COMPANYUNIQUEID INT,
	COMMUNITYUNIQUEID INT,
	EMAIL VARCHAR(20),
	PHONE VARCHAR(20),
	FAX VARCHAR(20)
);

--用户配置文件
CREATE TABLE USERPROFILES (
	USERPROFILEUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	TITLE VARCHAR(20),
	PICTURE VARCHAR(40),
	MANAGERUNIQUEID INT,
	CREATEDBY VARCHAR(20),
	CREATORUNIQUEID INT NOT NULL,
	DATECREATED TIMESTAMP,
	DATELASTMODIFIED TIMESTAMP,
	LASTLOGON TIMESTAMP,
	SEX VARCHAR(4),
	EMAIL VARCHAR(20),
	LOCATION VARCHAR(120),
	PHONE VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20)
);

--业务类型
CREATE TABLE BUSINESS (
	BUSINESSUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	CHECKLEVEL VARCHAR(4) NOT NULL,  --审档级别
	CODE VARCHAR(4) NOT NULL --快捷编码
);

--数据字典
CREATE TABLE DATADICTIONARY (
	DICTIONARYUNIQUEID SERIAL PRIMARY KEY,
	ITEMTYPE SMALLINT NOT NULL,      --数据项类别 1-号牌种类 2-材料名称
	ITEMNAME VARCHAR(51) NOT NULL,   --数据项名称
	CODE VARCHAR(7) NOT NULL       --快捷编码
);

--业务类型-数据字典
CREATE TABLE BUSINESSITEMS (
	ITEMUNIQUEID SERIAL PRIMARY KEY,
	BUSINESSCODE VARCHAR(4) NOT NULL,
	DICTIONARYCODE VARCHAR(7) NOT NULL
);

--机构-业务类型
CREATE TABLE COMPANYBUSINESSES (
	CBUNIQUEID SERIAL PRIMARY KEY,
	COMPANYUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--用户-业务类型
CREATE TABLE USERBUSINESSES (
	UBUNIQUEID SERIAL PRIMARY KEY,
	USERUNIQUEID INT NOT NULL,
	BUSINESSUNIQUEID INT NOT NULL
);

--上架号
CREATE TABLE FRAMENUMBER (
	FRAMEUNIQUEID SERIAL PRIMARY KEY,
	STOREHOUSENAME VARCHAR(20) NOT NULL, --库房名称
	FRAMECODE INT,--密集架号
	MAXCOLUMN INT NOT NULL,
	MAXROW INT NOT NULL,
	CELLCODE INT,--单元格号
	COL INT NOT NULL,
	ROW INT NOT NULL,
	VIN VARCHAR(50),--车辆识别代码
	CODE VARCHAR(20),--上架号，例如014-002-003-001(密集架号-列-行-文件夹序号）
	MAXFOLDER INT --单元格内最大文件夹数
);

----租户
--CREATE TABLE TENANTS (
--	TENANTUNIQUEID SERIAL PRIMARY KEY,
--	TENANTNAME VARCHAR(20) NOT NULL
--);
----社区-租户
--CREATE TABLE COMMUNITYTENANTS (
--	CTUNIQUEID SERIAL NOT NULL,
--	COMMUNITYUNIQUEID INT NOT NULL,
--	TENANTUNIQUEID INT NOT NULL,
--	FOREIGN KEY(COMMUNITYUNIQUEID) REFERENCES COMMUNITIES(COMMUNITYUNIQUEID),
--	FOREIGN KEY(TENANTUNIQUEID) REFERENCES TENANTS(TENANTUNIQUEID),
--	PRIMARY KEY(CTUNIQUEID, COMMUNITYUNIQUEID, TENANTUNIQUEID)
--);

/*
--站点
CREATE TABLE SITE (
	SITEUNIQUEID SERIAL PRIMARY KEY,
	SITENAME VARCHAR(20) NOT NULL,--站点名
	SITETYPE VARCHAR(20) NOT NULL,--站点类型
	HOSTADDR VARCHAR(50) NOT NULL,--主机地址
	PORT SMALLINT,--端口号
	DEFAULTREMOTEDIRECTORY VARCHAR(50), --默认目录
	USERNAME VARCHAR(20), --服务用户名
	PASSWORD VARCHAR(50), --密码
	MODE VARCHAR(10), --传输模式
	CHARSET VARCHAR(10), --字符集
	RUNNINGSTATUS SMALLINT NOT NULL, --运行状态 1运行 0停止
	CODE VARCHAR(7) NOT NULL --快捷编码
);

--站点容量
CREATE TABLE SITECAPACITY (
	SITECAPACITYUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	CAPACITY BIGINT,
	USEDSPACE BIGINT,
	UPDATETIMEMILLIS BIGINT,
	UNIT VARCHAR(4),
	UNITNUMBER VARCHAR(10),
	MAXBATCH INT, -- 最大批次数
	MAXBUSINESS INT -- 每批次内最大业务数
);

--站点内文件个数
CREATE TABLE SITEFOLDER (
	SITEFOLDERUNIQUEID SERIAL PRIMARY KEY,
	SITEUNIQUEID INT,
	BATCHCOUNT INT, --批次增长数
	BUSINESSCOUNT INT --业务数量
	
);
*/
--社区-站点
CREATE TABLE COMMUNITYSITES (
	CSUNIQUEID SERIAL NOT NULL,
	COMMUNITYUNIQUEID INT NOT NULL,
	SITEUNIQUEID INT NOT NULL,
	FOREIGN KEY (COMMUNITYUNIQUEID)
		REFERENCES COMMUNITIES (COMMUNITYUNIQUEID),
	FOREIGN KEY (SITEUNIQUEID)
		REFERENCES SITE (SITEUNIQUEID),
	PRIMARY KEY (CSUNIQUEID, COMMUNITYUNIQUEID, SITEUNIQUEID)
);
--消息系统
CREATE TABLE MESSAGES (
	MESSAGEUNIQUEID SERIAL PRIMARY KEY,
	SUBJECT VARCHAR(50) NOT NULL,--标题
	CONTENT VARCHAR(200) NOT NULL,--内容
	MATEDATA VARCHAR(200) NOT NULL,--元数据
	CREATORUNIQUEID INT NOT NULL,--创建者ID
	DATECREATED TIMESTAMP, -- 创建时间
	SENTTIMES SMALLINT NOT NULL,--已发送次数
	REMINDERFREQUENCYID INT NOT NULL, -- 发送频率ID
	DELETED SMALLINT NOT NULL
);
--消息接收者
CREATE TABLE MESSAGERECIPIENT (
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收方ID
	RECIPIENTNAME VARCHAR(50) NOT NULL,--接收方名称
	RECIPIENTTYPE SMALLINT NOT NULL, --接收方类别
	MESSAGEUNIQUEID INT NOT NULL -- 消息ID
);
--提醒频率
CREATE TABLE REMINDERFREQUENCY (
	FREQUENCYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20),
	FREQUENCY SMALLINT NOT NULL, -- 1-每天 7-每周
	ENABLED SMALLINT NOT NULL,--1-启用 0禁用
	STARTINGTIME TIMESTAMP,--起始时间
	ENDINGTIME TIMESTAMP -- 结束时间
);
--发送细节
CREATE TABLE SENDDETAILS(
	MESSAGERECIPIENTUNIQUEID SERIAL PRIMARY KEY,
	RECIPIENTUNIQUEID INT NOT NULL, --接收者UserID
	MESSAGEUNIQUEID INT NOT NULL, --消息ID
	MARKEDASREAD SMALLINT NOT NULL, --0-未读 1已读
	VIEWNAME VARCHAR(20) --视图名称，如果等于空则接收方将在首个视图上显示消息
);

--质检队列
CREATE TABLE QUEUE_1 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。质检只能取本社区和本机构的记录
);
--审档队列
CREATE TABLE QUEUE_2 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。普通审档只能取本社区和本机构的记录
);
--确认审档队列
CREATE TABLE QUEUE_3 (
	QUEUEUNIQUEID SERIAL PRIMARY KEY,
	UUID VARCHAR(40) NOT NULL,
	VIN VARCHAR(40),--车辆识别代码
	LOCKEDBYUSER INT,
	COMPANYUNIQUEID INT,--机构ID
	COMMUNITYUNIQUEID INT NOT NULL --社区ID。确认审档只能取本社区和本机构的记录
);
--角色表
CREATE TABLE ROLE (
	ROLEUNIQUEID SERIAL PRIMARY KEY,
	ROLENAME VARCHAR(20) NOT NULL,
	ROLETYPE VARCHAR(10) NOT NULL
);
--权限表
CREATE TABLE PERMISSION (
	PERMISSIONUNIQUEID SERIAL PRIMARY KEY,
	CATEGORYUNIQUEID INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL
);
--权限类别表
CREATE TABLE PERMISSIONCATEGORY (
	CATEGORYUNIQUEID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL
);
--用户与角色关系表
CREATE TABLE ROLEMEMBER (
	ROLEMEMBERUNIQUEID SERIAL NOT NULL,
	USERUNIQUEID INT NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	FOREIGN KEY (USERUNIQUEID)
		REFERENCES USERS (USERUNIQUEID),
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	PRIMARY KEY (ROLEMEMBERUNIQUEID, USERUNIQUEID, ROLEUNIQUEID)
);
--角色与权限关系表
CREATE TABLE ROLERIGHT (
	ROLERIGHTUNIQUEID SERIAL NOT NULL,
	ROLEUNIQUEID INT NOT NULL,
	PERMISSIONUNIQUEID INT NOT NULL,
	FOREIGN KEY (ROLEUNIQUEID)
		REFERENCES ROLE (ROLEUNIQUEID),
	FOREIGN KEY (PERMISSIONUNIQUEID)
		REFERENCES PERMISSION (PERMISSIONUNIQUEID),
	PRIMARY KEY (ROLERIGHTUNIQUEID, ROLEUNIQUEID, PERMISSIONUNIQUEID)
);
--批改建议
CREATE TABLE CORRECTINGSUGGESTIONS (
	SUGGESTIONUNIQUEID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	SUGGESTION VARCHAR(200) NOT NULL,
	FREQUENCY INT NOT NULL
);
--业务状态
CREATE TABLE BUSINESSSTATE (
	STATEUNIQUEID SERIAL PRIMARY KEY,
	CODE VARCHAR(60) NOT NULL,
	NAME VARCHAR(20) NOT NULL
);
--内嵌服务器
CREATE TABLE EMBEDDEDSERVER (
	SERVERUNIQUEID SERIAL PRIMARY KEY,
	SERVERNAME VARCHAR(20) NOT NULL,--站点名
	SERVERTYPE VARCHAR(20) NOT NULL,--站点类型
	HOSTADDR VARCHAR(50) NOT NULL,--主机地址
	PORT SMALLINT,--端口号
	DEFAULTREMOTEDIRECTORY VARCHAR(50), --默认目录
	USERNAME VARCHAR(20), --服务用户名
	PASSWORD VARCHAR(50), --密码
	RUNNINGSTATUS SMALLINT NOT NULL, --运行状态 1运行 0停止
	CODE VARCHAR(7) NOT NULL --快捷编码
);
--系统日志表
CREATE TABLE SYSTEMLOG (
	LOGUNIQUEID SERIAL PRIMARY KEY,
	LOGTYPE VARCHAR(20) NOT NULL,--日志类型
	USERNAME VARCHAR(20) NOT NULL,--操作者
	IPADDR VARCHAR(30),--操作者IP
	MODULEID INT NOT NULL,--模块ID
	DETAILS VARCHAR(200),--详细内容
	DATECREATED TIMESTAMP NOT NULL--创建日期
);
--通知表
CREATE TABLE NOTIFICATIONS (
	NOTIFICATIONUNIQUEID SERIAL PRIMARY KEY,
	WARNING BOOLEAN NOT NULL,--日志类型
	CONTENT VARCHAR(20) NOT NULL,--操作者
	RELATIVETIME TIMESTAMP NOT NULL,--操作者IP
	CHECKED INT NOT NULL,--模块ID
	USERNAME VARCHAR(200) NOT NULL--详细内容
);


RETURN;
END
$BODY$
LANGUAGE PLPGSQL;
 

--获取分页数
DROP FUNCTION IF EXISTS CREATE_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR);
CREATE OR REPLACE FUNCTION CREATE_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR) RETURNS SETOF INTEGER AS
$BODY$
DECLARE
  A INTEGER := 0;
  B INTEGER := 0;
  L INTEGER := 0;
BEGIN
	L := CHAR_LENGTH(KEYWORD);
	IF L = 0 THEN
		SELECT COUNT(IMAGINGUNIQUEID) INTO A FROM IMAGING;
	ELSE
		SELECT COUNT(IMAGINGUNIQUEID) INTO A FROM IMAGING WHERE PLATENUMBER ILIKE '%'||KEYWORD||'%';
	END IF;
   
    B := (A%LIMIT2); --RAISE NOTICE  '%', B;
   IF A <= LIMIT2 THEN
     RETURN NEXT 1;
   ELSIF B > 0 THEN 
     RETURN NEXT A/LIMIT2+1;
   ELSE
     RETURN NEXT A/LIMIT2;
   END IF;
   RETURN;
END
$BODY$
LANGUAGE PLPGSQL;

--分页页数
DROP FUNCTION IF EXISTS CREATE_PAGINGCOUNT2(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR);
CREATE OR REPLACE FUNCTION CREATE_PAGINGCOUNT2(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR) RETURNS BIGINT AS
$BODY$
DECLARE
  B INTEGER := 0;
  L INTEGER := 0;
  RS BIGINT := 0;
  TOTAL BIGINT := 0;
  EX_SQL VARCHAR;
BEGIN
   EX_SQL :='';
   L := CHAR_LENGTH(KEYWORD);
   --RAISE NOTICE '%', L;

   IF L = 7 OR L = 8 THEN --search by platenumber
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.PLATENUMBER ILIKE '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   ELSIF L = 15 THEN --search by barcode
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   ELSIF L = 19 THEN --search by vin
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.VIN ILIKE '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;
   ELSE  --search by all
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.VIN ILIKE '''||KEYWORD||''' OR A.BARCODE ILIKE '''||KEYWORD||''' OR A.PLATENUMBER ILIKE '''||KEYWORD||''' ';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   END IF;
    --RAISE NOTICE '%', TOTAL;

    B := (TOTAL%LIMIT2);
    IF TOTAL <= LIMIT2 THEN
     RETURN 1;
   ELSIF B > 0 THEN 
     RETURN TOTAL/LIMIT2+1;
   ELSE
     RETURN TOTAL/LIMIT2;
   END IF;
 
END
$BODY$
LANGUAGE PLPGSQL;

--获取模糊查询
CREATE OR REPLACE FUNCTION CREATE_SEARCH(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR) RETURNS SETOF RETURN_TABLE AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';
   IF LIMIT2 = -1 THEN
      LIMIT_STR := '';
   ELSE
      LIMIT_STR := ' LIMIT '''||LIMIT2||''' OFFSET '''||OFFSET2||'''';
   END IF;
   
   L := CHAR_LENGTH(KEYWORD);
   IF L = 7 OR L = 8 THEN --search by plateNumber
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.PLATENUMBER ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.PLATENUMBER ILIKE '''||KEYWORD||'''' || LIMIT_STR;
		 
   ELSIF L = 15 THEN  --search by barcode
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||'''' || LIMIT_STR;
   ELSIF L = 19 THEN  --search by VIN
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.VIN ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.VIN ILIKE '''||KEYWORD||'''' || LIMIT_STR;
   ELSE  --search by all
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||''' OR A.PLATENUMBER ILIKE '''||KEYWORD||''' OR A.VIN ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||''' OR A.PLATENUMBER ILIKE '''||KEYWORD||''' OR A.VIN ILIKE '''||KEYWORD||'''' || LIMIT_STR;

   END IF;
   
   --RAISE NOTICE '%', EX_SQL;
   RETURN QUERY EXECUTE EX_SQL;
END
$BODY$
LANGUAGE PLPGSQL;


DROP FUNCTION IF EXISTS INSERT_DATA();
CREATE OR REPLACE FUNCTION INSERT_DATA() RETURNS SETOF integer AS
$BODY$
BEGIN
	
	----插入社区
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('LN', '辽宁省社区', 1, 1);
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('DL', '大连市社区', 1, 2);
	INSERT INTO COMMUNITIES(COMMUNITYNAME, COMMUNITYDESCRIPTION, GROUPID, LEVEL) VALUES ('ZH', '庄河市社区', 1, 3);

	----插入机构
    INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (2,'大连市车管所','210000','210200','210202','泉水',1,NULL,0,'车管所');
 	INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (2,'大连市二手车市场','210000','210200','210211','泉水',0,NULL,1,'二手车');
   	INSERT INTO COMPANIES(COMMUNITYUNIQUEID,COMPANYNAME,PROVINCE,CITY,DISTRICT,ADDRESS,HASSTOREHOUSE,STOREHOUSENAME,IGNORECHECKER,CATEGORY) VALUES (3,'庄河市车管所','210000','210200','210283','',1,NULL,0,'车管所');

	
    --插入系统用户
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('system','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'',0,0,'sys1@max.com','047-5831-01',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (1,'系统管理员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','车','管');
	
	
	 --a
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('a','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'a@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (2,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','a','');
	
	--b
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('b','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'b@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (3,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','b','');
	
	--c
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('c','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'c@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (4,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','c','');
	
	--d
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('d','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'d@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (5,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','d','');
	
 	--e
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('e','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'e@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (6,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','e','');
	
	--f
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('f','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'f@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (7,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','f','');
	
	
	--g
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('g','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'g@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (8,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','g','');
	
	--h
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('h','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'h@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (9,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','h','');
	
	--i
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('i','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'i@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (10,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','i','');
	
	--j
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('j','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'j@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (11,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','j','');
	
	
	--k
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('k','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'大连市车管所',1,2,'k@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (12,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','k','');
	
	--l
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('l','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'庄河市车管所',3,3,'l@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (13,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','l','');
	
	
	--m
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('m','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'庄河市车管所',3,3,'m@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (14,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','m','');
	
	--n
	INSERT INTO USERS
		(USERNAME,HASHED,ACTIVATED,COMPANYNAME,COMPANYUNIQUEID,COMMUNITYUNIQUEID,EMAIL,PHONE,FAX)
	VALUES ('n','$2a$04$8DYZguxOXmsQJLaGebXE9eKvfgYudFPtmbCLk71TPmh0qDnHTumAO',1,'庄河市车管所',3,3,'n@max.com','047-5831-02',NULL);
	--插入系统用户个人配置
	INSERT INTO USERPROFILES
		(USERUNIQUEID,TITLE,PICTURE,MANAGERUNIQUEID,CREATEDBY,CREATORUNIQUEID,DATECREATED,DATELASTMODIFIED,LASTLOGON,SEX,EMAIL,LOCATION,PHONE,FIRSTNAME,LASTNAME)
	VALUES (15,'职员','img/adminmenu/users/user1.png',0,'system',1,CURRENT_TIMESTAMP,NULL,NULL,'','','','','n','');
	
	--插入系统权限类别
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('登录类别');--A 1
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('个人配置');--B 2
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理用户');--C 3
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理角色');--D 4
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理权限');--E 5
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理机构');--F 6
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理社区');--G 7
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('高拍仪');  --H 8
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理查询');--J 9
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理站点');--K 10
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('广播消息');--L 11
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('数据字典');--M 12
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('业务类型');--N 13
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理范围');--O 14
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理库房');--P 15
	INSERT INTO PERMISSIONCATEGORY(NAME) VALUES('管理服务器');--Q 16
	
	--插入所有权限
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A1','管理员','管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A2','前台','前台用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A3','质检','质检用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A4','审档','审档用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A5','查询','数据查询用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A6','上架下架','上架下架用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A7','确认审档','只对一级审档业务确认审档');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A8','影像化管理员','影像化管理员');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A9','影像化录入','影像化录入');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(1,'A10','影像化质检','影像化质检');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B1','更改个人资料','更改个人资料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(2,'B2','更改密码','更改密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C1','创建','创建用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C2','编辑','编辑用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C3','删除','删除用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C4','查看','查看用户列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C5','分配角色','为用户分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C6','分配业务','为用户分配业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(3,'C7','重置密码','为用户重置密码');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D1','创建','创建角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D2','编辑','编辑角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D3','删除','删除角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D4','分配用户','为角色分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D5','设置权限','为角色分配权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(4,'D6','查看','查看角色列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E1','分配角色','为权限分配角色');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E2','编辑','编辑权限');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(5,'E3','查看','查看权限列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F1','创建','创建机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F2','编辑','编辑机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F3','删除','删除机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F4','分配用户','为机构分配用户');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F5','管理库房','管理库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F6','查看','查看机构列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(6,'F7','设置','设置业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G1','创建','创建社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G2','编辑','编辑社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G3','删除','删除社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G4','分配机构','分配机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G5','查看','查看社区列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(7,'G6','分配站点','为社区分配站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(8,'H1','更改高拍仪','更改高拍仪');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(9,'J1','删除','删除业务记录及其所有原文');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K1','创建','创建站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K2','编辑','编辑站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K3','删除','删除站点');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K4','查看','查看站点列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K5','分配社区','为站点分配社区');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(10,'K6','操作','对站点进行启动/停止/测试连接操作');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L1','发送消息','发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L2','查看','查看消息列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L3','设置','设置定时发送消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(11,'L4','删除','删除消息');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M1','创建','创建数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M2','编辑','编辑数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M3','删除','删除数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(12,'M4','查看','查看数据字典');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N1','创建','创建业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N2','编辑','编辑业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N3','删除','删除业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N4','查看','查看业务类型');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(13,'N5','设置','设置业务材料');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'O1','社区范围内','社区管理员既可以管社区也可以管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(14,'O2','机构范围内','机构管理员只允许管机构');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P1','创建','创建库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P2','编辑','编辑库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P3','删除','删除库房');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P4','查看','查看库房列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P5','分配机构','为库房分配一个机构（通常机构是车管所）');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(15,'P6','管理密集架','管理密集架');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(16,'Q1','查看','查看服务器列表');
	INSERT INTO PERMISSION(CATEGORYUNIQUEID, CODE, NAME, DESCRIPTION) VALUES(16,'Q2','编辑','编辑服务器配置信息');
	
	--插入全部角色
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('系统管理员', '系统内置');	--1
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('前台', '自定义');	--2
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('质检', '自定义');	--3
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('审档', '自定义');	--4
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('查询', '自定义');	--5
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('上架下架', '自定义');	--6
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('确认审档', '自定义');	--7
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化管理员', '自定义');	--8
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化录入', '自定义');	--9
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('影像化质检', '自定义');	--10
	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连社区管理员', '自定义');	--11
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连车管所管理员', '自定义');	--12
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('庄河社区管理员', '自定义');	--13
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('庄河车管所管理员', '自定义');	--14
 	INSERT INTO ROLE(ROLENAME, ROLETYPE) VALUES('大连二手车管理员', '自定义');	--15

	
	--插入系统管理员权限
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,11);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,12);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,13);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,14);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,15);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,16);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,17);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,18);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,19);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,20);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,21);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,22);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,23);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,24);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,25);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,26);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,27);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,28);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,29);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,30);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,31);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,32);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,33);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,34);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,35);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,36);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,37);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,38);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,39);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,40);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,41);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,42);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,43);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,44);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,45);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,46);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,47);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,48);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,49);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,50);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,51);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,52);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,53);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,54);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,55);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,56);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,57);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,58);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,59);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,60);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,61);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,62);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,65);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,66);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,67);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,68);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,69);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,70);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,71);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,72);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,73);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,74);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,75);
--	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(1,76);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(2,2);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(3,3);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(4,4);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(5,5);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(6,6);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(7,7);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(8,8);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(9,9);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(10,10);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(11,1);
    INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(11,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(12,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(12,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(13,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(13,63);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(14,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(14,64);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(15,1);
	INSERT INTO ROLERIGHT(ROLEUNIQUEID, PERMISSIONUNIQUEID) VALUES(15,64);
	
	--插入system用户角色关系
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(1,1); --为system用设置角色
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(2,2);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(3,3);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(4,4);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(5,5);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(6,6);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(7,7);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(8,8);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(9,9);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(10,10);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(11,11);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(12,12);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(13,13);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(14,2);
	INSERT INTO ROLEMEMBER(USERUNIQUEID, ROLEUNIQUEID) VALUES(15,3);
	
	
	--插入业务类型
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补换领检验合格标志','无','YW33');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('影像化档案信息更正','无','YW34');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-变更备案','无','YW35');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('重新打刻车辆识别','无','0210');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-被套牌换发号牌恢复','无','YW36');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-重新打刻车辆识别代号','无','YW37');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换车身/车架','无','0025');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-被套牌换发号牌','无','YW38');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转出注销恢复收存资料','无','YW39');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('申领登记证书','无','YW40');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('抵押登记','无','YW41');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('质押备案','无','0006');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更共同所有人姓名/名称','无','0022');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记','无','0216');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('销毁机动车档案','无','YW42');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更机动车所有人姓名/名称','无','0021');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补换领、首次申领登记证书','无','YW43');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解除抵押登记','无','0005');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解除质押备案','无','YW44');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换整车','无','0027');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('住所迁出车管所管辖区域','无','0028');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('换领登记证书','无','YW45');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('注销和恢复驾驶资格','无','YW46');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('查封机动车档案','无','YW47');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-重新打刻发动机号码','无','YW48');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('加装残疾人操纵辅助装备','无','0214');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('嫌疑车辆调查','无','YW49');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('嫌疑车辆调查-排除嫌疑的机动车','无','YW50');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更使用性质','无','0023');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('更换发动机','无','0024');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-加装残疾人操纵辅助装置','无','YW51');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更车身颜色','无','0026');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更身份证明名称/号码','无','0211');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解封机动车档案收存资料','无','YW52');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-更换车身车架','无','YW53');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转出/注销恢复','无','0031');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-变更车身颜色','无','YW54');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('增加准驾车型申领','无','YW55');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('解除监管','无','0032');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('查阅机动车档案','无','YW56');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补领登记证书','无','0008');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-更换发动机','无','YW57');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转移登记','无','YW58');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('注销登记收存资料','无','YW59');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-变更使用性质','无','YW60');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('拆除残疾人操纵辅助装置','无','0215');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-变更联系方式','无','YW61');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('重新打刻发动机号码','无','0029');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-住所在车管所辖区内迁移','无','YW62');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('核发临时入境机动车牌证','无','YW63');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('注册登记','无','0001');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补换领行驶证','无','YW64');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('变更登记备案-共同所有人姓名变更登记','无','YW65');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补建机动车档案','无','YW66');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('转入机动车','无','YW67');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('补换领号牌','无','YW68');
	INSERT INTO BUSINESS(NAME,CHECKLEVEL,CODE) VALUES('登记事项更正','无','YW69');
	
	----数据字典 1:号牌种类
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'1-大型汽车','HPZL01');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'2-小型汽车','HPZL02');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'3-使馆汽车','HPZL03');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'4-领馆汽车','HPZL04');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'5-境外汽车','HPZL05');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'6-外籍汽车','HPZL06');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'7-普通摩托车','HPZL07');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'8-轻便摩托车','HPZL08');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'9-使馆摩托车','HPZL09');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'10-领馆摩托车','HPZL10');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'11-境外摩托车','HPZL11');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'12-外籍摩托车','HPZL12');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'13-低速车','HPZL13');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'14-拖拉机','HPZL14');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'15-挂车','HPZL15');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'16-教练汽车','HPZL16');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'17-教练摩托车','HPZL17');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'18-试验汽车','HPZL18');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'19-试验摩托车','HPZL19');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'20-临时入境汽车','HPZL20');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'21-临时入境摩托车','HPZL21');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'22-临时行使车','HPZL22');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'23-警用汽车','HPZL23');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'24-警用摩托','HPZL24');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'25-原农机号牌','HPZL25');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'26-香港入出境车','HPZL26');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'27-澳门入出境车','HPZL27');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'28-大型新能源汽车','HPZL28');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(1,'29-小型新能源汽车','HPZL29');
	
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'辽宁省','210000');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'大连市','210200');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'中山区','210202');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'西岗区','210203');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'沙河口区','210204');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'甘井子区','210211');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'旅顺口区','210212');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'金州区','210213');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'长海县','210224');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'瓦房店市','210281');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'普兰店区','210282');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(2,'庄河市','210283');
	
 	
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注册、转移、注销登记转入申请表》原件','CL01');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'发动机号码拓印膜','CL44');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'盗抢汽车立案证明复印件','CL45');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'介绍信原件','CL46');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其它证明、凭证的原件或者复印件','CL47');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'拍卖成交确认书复印件','CL48');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'警车号牌审批表原件','CL49');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关事项变更证明复印件','CL50');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆购置税完税证明副联原件','CL07');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'申请表','CL33');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车业务流程单','CL51');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《判决书》原件或者复印件','CL52');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'监销人和销毁人签字的销毁记录原件','CL53');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'公安交通管理撤销决定书原件','CL54');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'影像化档案信息更正申请表','CL38');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其它资料','CL32');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联原件或复印件','CL55');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术参数表','CL56');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'校车使用许可复印件','CL57');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车变更登记备案申请表','CL18');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'身体条件证明','CL58');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车的来历证明原件或复印件','CL21');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车勘误登记申请表','CL23');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《中华人民共和国海关监管车辆解除监管证明书》原件','CL59');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》;人民检察院、行政执法部门未得到登记证书证明','CL12');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车牌证申请表','CL24');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联原件或者复印件','CL60');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《报废汽车回收证明》复印件','CL61');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'委托书原件','CL62');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《裁定书》复印件','CL63');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车所有人身份证明复印件','CL64');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'中国海关等部门准许入境的凭证复印件','CL65');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料记录','CL66');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'询问记录','CL67');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'出境证明复印件','CL68');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'仲裁机构出具的《仲裁裁决书》原件或复印件','CL69');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关证明或手续原件','CL70');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'承诺书原件','CL71');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原登记证书原件','CL72');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'档案查询公函原件','CL73');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车船税完税证明复印件','CL74');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位注销证明复印件','CL75');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车驾驶证原件','CL76');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车所有人身份证明','CL40');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车交通事故责任强制保险凭证第三联原件','CL77');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行驶证原件','CL37');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'登记证书原件','CL78');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车抵押登记或者质押备案申请表》原件','CL79');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更证明','CL05');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车安全技术检验合格证明','CL17');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车来历证明复印件','CL80');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'共同所有的公证证明或证明夫妻关系的居民户口簿和结婚证','CL14');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车查验记录表原件','CL19');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现机动车所有人身份证明','CL36');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'拓印膜','A043');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进口车5部位照片','CL29');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'合格证','CL15');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原合格证','CL39');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押权人身份证明','CL09');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'该机动车在系统中的所有记录信息','CL13');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'公函原件','CL81');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车标准照片','CL82');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《裁定书》复印件','CL83');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'安全技术检验合格证明','CL02');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'未得到登记证书的证明原件','CL84');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'依法收缴的法律文书复印件','CL85');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《判决书》复印件','CL86');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'核对公函','CL16');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位吊销证明复印件','CL87');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'经办人工作证明复印件','CL88');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车业务流程记录单','CL89');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车抵押登记或者质押备案申请表','CL22');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'代办人身份证明复印件','CL90');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'退车证明原件','CL91');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'驾驶技能准考证明','CL92');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准补建机动车档案文件','CL30');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'海关批准的转让证明原件','CL93');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《判决书》原件或复印件','CL94');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交通强险第三联原件','CL95');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'调查取证材料原件','CL96');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押权人身份证明复印件','CL97');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《仲裁裁决书》复印件','CL98');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术鉴定证明复印件','CL99');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'询问笔录原件','CL100');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'解体照片','CL101');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车识别代号拓印膜','CL102');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行政处罚决定书复印件','CL103');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《居民户口簿》复印件','CL104');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'解除监管证明书','CL28');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注册、转移、注销登记或转入申请表》复印件','CL105');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'罚没款收据复印件','CL106');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'灭失证明原件','CL107');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车档案补录档案更正申请表》','CL108');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'行政强制措施凭证（滞留车辆）原件','CL109');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明','CL10');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现合格证','CL35');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有权转移证明','CL25');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车安全技术检验合格证明原件','CL110');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《调解书》原件或者复印件','CL111');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆使用性质证明原件','CL112');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'嫌疑车辆移交清单原件','CL113');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'操纵辅助装置加装合格证明','CL06');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料','CL20');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'现机动车所有人身份证明复印件','CL114');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'原机动车档案','CL115');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车整车出厂合格证明复印件','CL116');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联原件','CL117');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'报废机动车回收证明原件','CL118');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'受案登记表复印件','CL119');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《判决书》复印件','CL120');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'书面报告原件','CL121');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车变更登记备案申请表》原件','CL122');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关证明或者手续原件','CL123');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'重复核对报告表复印件','CL124');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'驾驶人考试成绩单','CL125');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'公安机关发还证明复印件','CL126');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其资它料','CL127');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车档案资料目录','CL128');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更前机动车所有人身份证明','CL03');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准文件原件','CL129');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'进（出）境领（销）牌照通知书原件','CL130');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《结婚证》复印件','CL131');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'核对公函原件','CL132');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'典当行身份证明复印件','CL133');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'批准补建机动车档案的文件原件','CL134');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车被盗抢证明》原件或者复印件','CL135');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'驾驶培训记录单','CL136');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》、《裁定书》、《判决书》、《协助执行通知书》','CL11');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押合同','CL08');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车登记证明复印件','CL137');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其他资料','CL31');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'发动机号码拓印膜原件','CL138');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'办案单位公函原件','CL139');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'技术鉴定证明或公安机关发还证明','CL27');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车牌证申请表》原件','CL140');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'两人以上共同所有的公证证明复印件','CL141');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《裁定书》原件或复印件','CL142');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'变更使用性质证明','CL04');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'身份证明复印件(暂住证)','CL143');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车管所书面记载调查情况','CL144');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'转出注销相关资料','CL41');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《调解书》复印件','CL145');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车所有人身份证明复印件','CL26');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'有关证据','CL146');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'科研、定型试验书面申请原件','CL147');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车驾驶人档案目录','CL148');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《裁定书》原件或者复印件','CL149');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'法院《调解书》复印件','CL150');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'抵押合同原件或者复印件','CL151');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'交强险第三联复印件','CL152');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车注销证明书》原件','CL153');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位注销查询卡复印件','CL154');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'相关部门证明原件','CL155');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《影像化档案信息更正申请表》原件','CL156');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车识别代号拓印膜原件','CL157');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'其他证明、凭证的原件或者复印件','CL158');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'中文翻译文本原件','CL159');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'书面报告','CL34');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'肢体残疾人操纵辅助装置加装合格证明复印件','CL160');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'人民法院出具的《调解书》原件或复印件','CL161');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'转出注销恢复证明原件','CL162');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'控购证明原件','CL163');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《协助执行通知书》原件','CL164');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'待销毁的机动车档案清单','CL165');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'单位吊销查询卡复印件','CL166');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车被盗抢证明》原件或复印件','CL167');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车来历证明原件或复印件者','CL168');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《临时入境机动车号牌、行驶证申请表》原件','CL169');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《机动车勘误登记申请表》原件','CL170');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'车辆照片','A042');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'《申请恢复机动车登记业务审批表》原件','CL171');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'机动车驾驶证申请表','CL172');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'有组织的旅游、比赛以及其他交往活动的证明原件','CL173');
	INSERT INTO DATADICTIONARY(ITEMTYPE,ITEMNAME,CODE) VALUES(3,'仲裁机构出具的《仲裁裁决书》原件或者复印件','CL174');

 	--插入业务材料关系
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL01');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL02');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL03');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL04');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL05');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL06');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL07');
	INSERT INTO BUSINESSITEMS(BUSINESSCODE,DICTIONARYCODE) VALUES('0001', 'CL39');
	
	 	
    ----插入系统设置
    INSERT INTO SYSTEM_SETTINGS(K, V) VALUES ('高拍仪', '无锡华通H6-1'); --默认使用无锡华通H6-1
    ----默认站点
 --   INSERT INTO SITE(SITENAME,SITETYPE,HOSTADDR,PORT,DEFAULTREMOTEDIRECTORY,USERNAME,PASSWORD,MODE,CHARSET,RUNNINGSTATUS,CODE) VALUES('文件站点1','File','C:\Demo\pictures',0,'/','','','主动','UTF-8',1,'DL01');
 --   INSERT INTO SITECAPACITY(SITEUNIQUEID, CAPACITY, USEDSPACE, UPDATETIMEMILLIS, UNIT, UNITNUMBER, MAXBATCH, MAXBUSINESS) VALUES (1, 2199023255552, 0, 1538146213038, 'TB', 2, 1000,3000);
 --   INSERT INTO SITEFOLDER(SITEUNIQUEID, BATCHCOUNT, BUSINESSCOUNT) VALUES (1, 1, 0);

    ----站点和社区关系
    INSERT INTO COMMUNITYSITES(COMMUNITYUNIQUEID, SITEUNIQUEID) VALUES (2, 1);
    INSERT INTO COMMUNITYSITES(COMMUNITYUNIQUEID, SITEUNIQUEID) VALUES (3, 1);
 	
    --业务状态
    INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B1','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B2','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B3','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B4','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B5','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B6','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B7','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B8','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B9','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B10','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B11','已入库');
	INSERT INTO BUSINESSSTATE(CODE, NAME) VALUES('B12','已入库');
    
  RETURN;
END
$BODY$
LANGUAGE plpgsql;
 
SELECT * FROM CREATE_TABLES();

SELECT * FROM INSERT_DATA();

SELECT * FROM CREATE_PAGINGCOUNT(3,'');

SELECT * FROM CREATE_PAGINGCOUNT2(20, '%'||'11'||'%','DL');

SELECT * FROM CREATE_SEARCH(20,0,'%'||'11111111111111111'||'%','DL');


