DROP FUNCTION IF EXISTS SEARCH_BY_KEYWORD_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR,LOCATION VARCHAR);
CREATE OR REPLACE FUNCTION SEARCH_BY_KEYWORD_PAGINGCOUNT(LIMIT2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR,LOCATION VARCHAR) RETURNS BIGINT AS
$BODY$
DECLARE
  B INTEGER := 0;
  L INTEGER := 0;
  RS BIGINT := 0;
  TOTAL BIGINT := 0;
  EX_SQL VARCHAR;
BEGIN
   EX_SQL :='';
   L := CHAR_LENGTH(KEYWORD);
  RAISE NOTICE '%', L;
RAISE NOTICE '%', KEYWORD;

   IF L = 5 OR L = 6 THEN --search by platenumber
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.PLATENUMBER = '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   ELSIF L = 13 THEN --search by barcode
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.BARCODE = '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   ELSIF L = 17 THEN --search by vin
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.VIN = '''||KEYWORD||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;
   ELSE  --search by all
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.BARCODE ILIKE ''%'||KEYWORD||'%''  ';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   END IF;
    --RAISE NOTICE '%', TOTAL;

    B := (TOTAL%LIMIT2);
    IF TOTAL <= LIMIT2 THEN
     RETURN 1;
   ELSIF B > 0 THEN 
     RETURN TOTAL/LIMIT2+1;
   ELSE
     RETURN TOTAL/LIMIT2;
   END IF;
 
END
$BODY$
LANGUAGE PLPGSQL;
SELECT * FROM SEARCH_BY_KEYWORD_PAGINGCOUNT(20, '1','DL','210000,212000');