CREATE OR REPLACE FUNCTION SEARCH_BY_KEYWORD(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR) RETURNS SETOF RETURN_TABLE AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';
   IF LIMIT2 = -1 THEN
      LIMIT_STR := '';
   ELSE
      LIMIT_STR := ' LIMIT '''||LIMIT2||''' OFFSET '''||OFFSET2||'''';
   END IF;
   
   L := CHAR_LENGTH(KEYWORD);
   IF L = 7 OR L = 8 THEN --search by plateNumber
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.PLATENUMBER ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.PLATENUMBER ILIKE '''||KEYWORD||'''' || LIMIT_STR;
		 
   ELSIF L = 15 THEN  --search by barcode
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||'''' || LIMIT_STR;
   ELSIF L = 19 THEN  --search by VIN
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.VIN ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.VIN ILIKE '''||KEYWORD||'''' || LIMIT_STR;
   ELSE  --search by all
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||''' OR A.PLATENUMBER ILIKE '''||KEYWORD||''' OR A.VIN ILIKE '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.BARCODE ILIKE '''||KEYWORD||''' OR A.PLATENUMBER ILIKE '''||KEYWORD||''' OR A.VIN ILIKE '''||KEYWORD||'''' || LIMIT_STR;

   END IF;
   
   --RAISE NOTICE '%', EX_SQL;
   RETURN QUERY EXECUTE EX_SQL;
END
$BODY$
LANGUAGE PLPGSQL;
SELECT * FROM SEARCH_BY_KEYWORD(20,0,'%'||'1'||'%','DL');