DROP FUNCTION IF EXISTS SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN_PAGINGCOUNT(LIMIT2 INT,PLATETYPE VARCHAR,PLATENUMBER VARCHAR,VIN VARCHAR,COMMUNITYNAME VARCHAR);
CREATE OR REPLACE FUNCTION SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN_PAGINGCOUNT(LIMIT2 INT,PLATETYPE VARCHAR,PLATENUMBER VARCHAR,VIN VARCHAR,COMMUNITYNAME VARCHAR) RETURNS BIGINT AS
$BODY$
DECLARE
  B INTEGER := 0;
  L INTEGER := 0;
  RS BIGINT := 0;
  TOTAL BIGINT := 0;
  EX_SQL VARCHAR;
BEGIN
   EX_SQL :='';
   
 
	FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(A.TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE = B.CODE WHERE A.PLATETYPE='''||PLATETYPE||''' AND A.PLATENUMBER='''||PLATENUMBER||''' OR A.VIN='''||VIN||'''';
	EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   
    --RAISE NOTICE '%', TOTAL;

    B := (TOTAL%LIMIT2);
    IF TOTAL <= LIMIT2 THEN
     RETURN 1;
   ELSIF B > 0 THEN 
     RETURN TOTAL/LIMIT2+1;
   ELSE
     RETURN TOTAL/LIMIT2;
   END IF;
 
END
$BODY$
LANGUAGE PLPGSQL;

SELECT * FROM SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN_PAGINGCOUNT(20,0,'','','1','DL');