DROP FUNCTION IF EXISTS SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN(LIMIT2 INT,OFFSET2 INT,PLATETYPE VARCHAR,PLATENUMBER VARCHAR,VIN VARCHAR,COMMUNITYNAME VARCHAR);
CREATE OR REPLACE FUNCTION SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN(LIMIT2 INT,OFFSET2 INT,PLATETYPE VARCHAR,PLATENUMBER VARCHAR,VIN VARCHAR,COMMUNITYNAME VARCHAR) RETURNS SETOF RETURN_TABLE AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';
   IF LIMIT2 = -1 THEN
      LIMIT_STR := '';
   ELSE
      LIMIT_STR := ' LIMIT '''||LIMIT2||''' OFFSET '''||OFFSET2||'''';
   END IF;
   
 
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.PLATETYPE='''||PLATETYPE||''' AND A.PLATENUMBER='''||PLATENUMBER||''' OR A.VIN='''||VIN||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.PLATETYPE='''||PLATETYPE||''' AND A.PLATENUMBER='''||PLATENUMBER||'''  OR A.VIN='''||VIN||'''' || LIMIT_STR;
 
 
   
   --RAISE NOTICE '%', EX_SQL;
   RETURN QUERY EXECUTE EX_SQL;
END
$BODY$
LANGUAGE PLPGSQL;

SELECT * FROM SEARCH_BY_PLATETYPE_AND_PLATENUMBER_OR_VIN(20,0,'','','11','DL');