
DROP FUNCTION IF EXISTS SELECT_DISTINCT_BUSINESSCODE_FROM_256(COMMUNITYNAME VARCHAR);
CREATE OR REPLACE FUNCTION SELECT_DISTINCT_BUSINESSCODE_FROM_256(COMMUNITYNAME VARCHAR) RETURNS SETOF VARCHAR AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN

    EX_SQL :='DROP VIEW IF EXISTS BUSINESSCODEVIEW';
       EXECUTE EX_SQL;
    EX_SQL :='CREATE TEMP VIEW BUSINESSCODEVIEW AS ';

        FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT DISTINCT BUSINESSCODE FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||'  UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT DISTINCT BUSINESSCODE FROM "'||COMMUNITYNAME||'".TRANSACTION_255';

        EXECUTE EX_SQL;

	EX_SQL :='SELECT DISTINCT BUSINESSCODE FROM BUSINESSCODEVIEW';

       
   --RAISE NOTICE '%', EX_SQL;
   RETURN QUERY EXECUTE EX_SQL;
END
$BODY$
LANGUAGE PLPGSQL;
SELECT * FROM SELECT_DISTINCT_BUSINESSCODE_FROM_256('DL');