DROP FUNCTION IF EXISTS DELETE_TRANSACTION_BY_BUSINESSCODE(COMMUNITYNAME VARCHAR,BUSINESSCODE VARCHAR);
CREATE OR REPLACE FUNCTION DELETE_TRANSACTION_BY_BUSINESSCODE(COMMUNITYNAME VARCHAR,BUSINESSCODE VARCHAR) RETURNS INT AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';

	FOR I IN 0..255 LOOP
		EX_SQL := 'DELETE FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE BUSINESSCODE='''||BUSINESSCODE||''' ';
		EXECUTE EX_SQL;
	END LOOP;

   
   --RAISE NOTICE '%', EX_SQL;
   RETURN 0;
END
$BODY$
LANGUAGE PLPGSQL;
SELECT * FROM DELETE_BUSINESSCODE('DL','0001');