DROP FUNCTION IF EXISTS GET_TOTAL_COUNT_FROM_256(COMMUNITYNAME VARCHAR);
CREATE OR REPLACE FUNCTION GET_TOTAL_COUNT_FROM_256(COMMUNITYNAME VARCHAR) RETURNS BIGINT AS
$BODY$
DECLARE
  B INTEGER := 0;
  L INTEGER := 0;
  RS BIGINT := 0;
  TOTAL BIGINT := 0;
  EX_SQL VARCHAR;
BEGIN
   EX_SQL :='';
    
   FOR I IN 0..255 LOOP
	   EX_SQL := 'SELECT COUNT(TRANSACTIONUNIQUEID) FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' WHERE CODE IS NOT NULL';
	   EXECUTE EX_SQL INTO RS;
	   TOTAL := TOTAL + RS;
	END LOOP;

   
    RAISE NOTICE '%', TOTAL;
    
    RETURN TOTAL;
 
END
$BODY$
LANGUAGE PLPGSQL;

SELECT * FROM GET_TOTAL_COUNT_FROM_256('DL');