CREATE OR REPLACE FUNCTION SEARCH_BY_KEYWORD(LIMIT2 INT,OFFSET2 INT,KEYWORD VARCHAR,COMMUNITYNAME VARCHAR,LOCATION VARCHAR) RETURNS SETOF RETURN_TABLE AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';
   IF LIMIT2 = -1 THEN
      LIMIT_STR := '';
   ELSE
      LIMIT_STR := ' LIMIT '''||LIMIT2||''' OFFSET '''||OFFSET2||'''';
   END IF;
   
   L := CHAR_LENGTH(KEYWORD);

RAISE NOTICE '%', L;
RAISE NOTICE '%', KEYWORD;
   
   IF L = 5 OR L = 6 THEN --search by plateNumber
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.PLATENUMBER = '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.PLATENUMBER = '''||KEYWORD||'''' || LIMIT_STR;
		 
   ELSIF L = 13 THEN  --search by barcode
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.BARCODE = '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.BARCODE = '''||KEYWORD||'''' || LIMIT_STR;
   ELSIF L = 17 THEN  --search by VIN
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.VIN = '''||KEYWORD||''' UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.VIN = '''||KEYWORD||'''' || LIMIT_STR;
   ELSE  --default search by barcode
	FOR I IN 0..254 LOOP
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_'||I||' AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.BARCODE ILIKE ''%'||KEYWORD||'%''  UNION ALL ';
	END LOOP;
		EX_SQL := EX_SQL || 'SELECT A.*,B.NAME AS BUSINESSNAME FROM "'||COMMUNITYNAME||'".TRANSACTION_255 AS A LEFT JOIN BUSINESS AS B ON A.BUSINESSCODE=B.CODE WHERE A.LOCATIONCODE LIKE '''||LOCATION||'%'' AND A.BARCODE ILIKE ''%'||KEYWORD||'%''' || LIMIT_STR;

   END IF;
   
   --RAISE NOTICE '%', EX_SQL;
   RETURN QUERY EXECUTE EX_SQL;
END
$BODY$
LANGUAGE PLPGSQL;
--SELECT * FROM SEARCH_BY_KEYWORD(20,0,'%'||'1'||'%','DL','210000,212000,210283');


SELECT * FROM SEARCH_BY_KEYWORD(20,0,'11111','DL','210000,210200');
