
DROP FUNCTION IF EXISTS UPDATE_BUSINESSCODE_IN_256(COMMUNITYNAME VARCHAR, OLDBUSINESSCODE VARCHAR, NEWBUSINESSCODE VARCHAR);
CREATE OR REPLACE FUNCTION UPDATE_BUSINESSCODE_IN_256(COMMUNITYNAME VARCHAR,OLDBUSINESSCODE VARCHAR, NEWBUSINESSCODE VARCHAR) RETURNS INT AS
$BODY$
DECLARE
  L INTEGER := 0;
  EX_SQL VARCHAR;
  LIMIT_STR VARCHAR;
BEGIN
   EX_SQL :='';

	FOR I IN 0..255 LOOP
		EX_SQL := 'UPDATE "'||COMMUNITYNAME||'".TRANSACTION_'||I||' SET BUSINESSCODE='''||NEWBUSINESSCODE||''' WHERE BUSINESSCODE='''||OLDBUSINESSCODE||''' ';
		EXECUTE EX_SQL;
	END LOOP;

   --RAISE NOTICE '%', EX_SQL;
   RETURN 0;
END
$BODY$
LANGUAGE PLPGSQL;
SELECT * FROM UPDATE_BUSINESSCODE_IN_256('DL','0001','9999');